window.chara=[
    {
		"id": "243",
		"assetid": "00003",
		"name": "Hinata Hyuga",
		"subname": "Blooming Taleng",
		"affi": "Konoha",
		"type": "HRT",
		"cost": "60",
		"rarity": "6",
		"limitbreak" "1",
		"chakra": "3",
		"hp": "1604",
		"lbhp": "2184",
		"atk": "1234",
		"lbatk": "1784",
		"range": "mid",
		"field": "Reduces chance of being immobilized by 20% - 25% (Not F Skills)",
		"buddy": "Reduces chance of being immobilized by 25% ( Not F Skills)",
		"ability1": "immobilized",
		"ability1desc": "10",
		"ability2": "atk",
		"ability2desc": "100",
		"ability3": "immobilized",
		"ability3desc": "10",
		"ability4": "hp",
		"ability4desc": "100",
		"ability5": "attackreduction",
		"ability5desc": "10",
		"ability6": "",
		"ability6desc": "",
		"skill1": "",
		"skill1desc": "For 5 turns, block up to 1000 damage as well as have 20% dodge chance.",
		"target1": "3",
		"skill2": "",
		"skill2desc": "7x ATK in HRT damage to 1 enemy, 70% chance to reduce attack for 5 turns.",
		"target2": "1"
	},
	
]