window.unusual=[
  {
    "cardUnusualId": "12",
    "category": "2",
    "iconId": "1005",
    "name": "封印",
    "description": "スキル使用不可になる",
    "subScore": "1",
    "color": "10066312",
    "type": "3",
    "normal": [20070209],
    "normal_hint": ["Chance"],
    "ignore": [60070901],
    "ignore_hint": ["Very High Chance"],
    "preemptive": [20070604],
    "preemptive_hint": ["High chance if there's a Konoha enemy"],
    "death": [20060602],
    "death_hint": ["Guarantee"],
    "counter": [20050303],
    "counter_hint": ["While 'Yata Mirror' is Active"],
    "perturn": [20070506],
    "perturn_hint": ["While 'Sacred Treasure of the Wicked Eye' is active'"],
  },
]