window.vo=[
        {
          "cardVoiceId": "1",
          "cardId": "20001782",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_02",
          "voiceSkill1": "naruto_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_02",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "2",
          "cardId": "20001776",
          "dirName": "naruto",
          "evolutionStep": "6",
          "voiceAppear": "naruto_battle_02_05",
          "voiceSkill1": "naruto_skill_01_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_04",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "3",
          "cardId": "20001777",
          "dirName": "sasuke",
          "evolutionStep": "6",
          "voiceAppear": "sasuke_battle_02_02",
          "voiceSkill1": "sasuke_skill_02_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_02",
          "voiceDeath": "sasuke_death_02_03"
        },
        {
          "cardVoiceId": "4",
          "cardId": "20001807",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_01",
          "voiceSkill1": "sasuke_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_01",
          "voiceDeath": "sasuke_death_02_02"
        },
        {
          "cardVoiceId": "5",
          "cardId": "20001813",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_battle_02_01",
          "voiceSkill1": "sakura_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_02_01",
          "voiceDeath": "sakura_death_02_01"
        },
        {
          "cardVoiceId": "6",
          "cardId": "20001817",
          "dirName": "hinata",
          "evolutionStep": "",
          "voiceAppear": "hinata_battle_02_01",
          "voiceSkill1": "hinata_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hinata_win_02_01",
          "voiceDeath": "hinata_death_02_01"
        },
        {
          "cardVoiceId": "7",
          "cardId": "20001818",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_battle_02_01",
          "voiceSkill1": "kakasi_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_win_02_02",
          "voiceDeath": "kakasi_death_02_01"
        },
        {
          "cardVoiceId": "8",
          "cardId": "20001834",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_battle_02_01",
          "voiceSkill1": "kakasi_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_win_02_02",
          "voiceDeath": "kakasi_death_02_01"
        },
        {
          "cardVoiceId": "9",
          "cardId": "20030501",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_10",
          "voiceSkill1": "naruto_skill_02_12,naruto_skill_02_21,naruto_skill_02_22",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_06",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "10",
          "cardId": "20030502",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_04",
          "voiceSkill1": "sasuke_skill_02_09,sasuke_skill_02_10,sasuke_skill_02_07,sasuke_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_03",
          "voiceDeath": "sasuke_death_02_04"
        },
        {
          "cardVoiceId": "11",
          "cardId": "20030503",
          "dirName": "naruto",
          "evolutionStep": "6",
          "voiceAppear": "naruto_battle_02_03",
          "voiceSkill1": "naruto_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "12",
          "cardId": "20030504",
          "dirName": "sasuke",
          "evolutionStep": "6",
          "voiceAppear": "sasuke_pursuit_01_02",
          "voiceSkill1": "sasuke_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_02",
          "voiceDeath": "sasuke_death_02_03"
        },
        {
          "cardVoiceId": "13",
          "cardId": "20030505",
          "dirName": "sakura",
          "evolutionStep": "6",
          "voiceAppear": "sakura_battle_02_02",
          "voiceSkill1": "sakura_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_02_02",
          "voiceDeath": "sakura_death_02_02"
        },
        {
          "cardVoiceId": "14",
          "cardId": "20030601",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_11",
          "voiceSkill1": "naruto_skill_02_18",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_death_02_02"
        },
        {
          "cardVoiceId": "15",
          "cardId": "20030602",
          "dirName": "minato",
          "evolutionStep": "",
          "voiceAppear": "minato_battle_02_04",
          "voiceSkill1": "minato_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "minato_win_02_03",
          "voiceDeath": "minato_death_02_02"
        },
        {
          "cardVoiceId": "16",
          "cardId": "20001860",
          "dirName": "naruto",
          "evolutionStep": "6",
          "voiceAppear": "naruto_battle_03_01",
          "voiceSkill1": "naruto_skill_03_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_03_01",
          "voiceDeath": "naruto_death_03_01"
        },
        {
          "cardVoiceId": "17",
          "cardId": "20001857",
          "dirName": "sakura",
          "evolutionStep": "6",
          "voiceAppear": "sakura_battle_03_01",
          "voiceSkill1": "sakura_skill_03_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_03_01",
          "voiceDeath": "sakura_death_03_01"
        },
        {
          "cardVoiceId": "18",
          "cardId": "20001848",
          "dirName": "sasuke",
          "evolutionStep": "6",
          "voiceAppear": "sasuke_battle_03_02",
          "voiceSkill1": "sasuke_battle_03_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_03_01",
          "voiceDeath": "sasuke_death_03_02"
        },
        {
          "cardVoiceId": "19",
          "cardId": "20030611",
          "dirName": "itachi",
          "evolutionStep": "",
          "voiceAppear": "itachi_battle_02_03",
          "voiceSkill1": "itachi_skill_02_07",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "itachi_win_02_03",
          "voiceDeath": "itachi_death_02_01"
        },
        {
          "cardVoiceId": "20",
          "cardId": "20001779",
          "dirName": "kabuto",
          "evolutionStep": "6",
          "voiceAppear": "kabuto_battle_02_03",
          "voiceSkill1": "kabuto_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kabuto_win_02_02",
          "voiceDeath": "kabuto_death_02_02"
        },
        {
          "cardVoiceId": "21",
          "cardId": "20030701",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_02",
          "voiceSkill1": "naruto_battle_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_02",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "22",
          "cardId": "20030702",
          "dirName": "jiraiya",
          "evolutionStep": "",
          "voiceAppear": "jiraiya_battle_02_01,jiraiya_battle_02_02",
          "voiceSkill1": "jiraiya_pursuit_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "jiraiya_win_02_03",
          "voiceDeath": "jiraiya_death_02_01"
        },
        {
          "cardVoiceId": "23",
          "cardId": "20030703",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_battle_02_01",
          "voiceSkill1": "hashirama_skill_02_01,hashirama_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hashirama_win_02_02",
          "voiceDeath": "hashirama_death_02_01"
        },
        {
          "cardVoiceId": "24",
          "cardId": "20030709",
          "dirName": "kushina",
          "evolutionStep": "",
          "voiceAppear": "kushina_battle_02_01",
          "voiceSkill1": "kushina_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kushina_win_02_01",
          "voiceDeath": "kushina_death_02_01"
        },
        {
          "cardVoiceId": "25",
          "cardId": "20030715",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_skill_02_17",
          "voiceSkill1": "sasuke_skill_02_14,sasuke_skill_02_1",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_05",
          "voiceDeath": "sasuke_death_02_05"
        },
        {
          "cardVoiceId": "26",
          "cardId": "20030802",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_09",
          "voiceSkill1": "naruto_skill_02_13,kurama_attack_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_01",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "27",
          "cardId": "20030803",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_03",
          "voiceSkill1": "sasuke_skill_02_13",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_04",
          "voiceDeath": "sasuke_death_02_04"
        },
        {
          "cardVoiceId": "28",
          "cardId": "20030816",
          "dirName": "guy",
          "evolutionStep": "",
          "voiceAppear": "guy_battle_02_03",
          "voiceSkill1": "guy_skill_02_16,guy_skill_02_17,guy_skill_02_18",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "guy_death_02_03",
          "voiceDeath": "guy_death_02_02"
        },
        {
          "cardVoiceId": "29",
          "cardId": "20001713",
          "dirName": "guy",
          "evolutionStep": "6",
          "voiceAppear": "guy_pursuit_02_01",
          "voiceSkill1": "guy_skill_02_18",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "guy_death_02_01",
          "voiceDeath": "guy_death_02_02"
        },
        {
          "cardVoiceId": "30",
          "cardId": "20030806",
          "dirName": "tsunade",
          "evolutionStep": "",
          "voiceAppear": "tsunade_battle_02_02",
          "voiceSkill1": "tsunade_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "tsunade_win_02_02",
          "voiceDeath": "tsunade_death_02_02"
        },
        {
          "cardVoiceId": "31",
          "cardId": "20030807",
          "dirName": "gaara",
          "evolutionStep": "",
          "voiceAppear": "gaara_battle_02_01",
          "voiceSkill1": "gaara_skill_02_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "gaara_win_02_03",
          "voiceDeath": "gaara_death_02_01"
        },
        {
          "cardVoiceId": "32",
          "cardId": "20030808",
          "dirName": "oonoki",
          "evolutionStep": "",
          "voiceAppear": "oonoki_battle_02_02",
          "voiceSkill1": "oonoki_skill_02_07",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "oonoki_win_02_01",
          "voiceDeath": "oonoki_death_02_01"
        },
        {
          "cardVoiceId": "33",
          "cardId": "20030809",
          "dirName": "a",
          "evolutionStep": "",
          "voiceAppear": "a_battle_02_01",
          "voiceSkill1": "a_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "a_win_02_02",
          "voiceDeath": "a_death_02_01"
        },
        {
          "cardVoiceId": "34",
          "cardId": "20030810",
          "dirName": "mei",
          "evolutionStep": "",
          "voiceAppear": "mei_battle_02_01",
          "voiceSkill1": "mei_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "mei_win_02_03",
          "voiceDeath": "mei_death_02_02"
        },
        {
          "cardVoiceId": "35",
          "cardId": "20030811",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_battle_02_03",
          "voiceSkill1": "hashirama_skill_02_02",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "hashirama_win_02_01",
          "voiceDeath": "hashirama_death_02_03"
        },
        {
          "cardVoiceId": "36",
          "cardId": "20030812",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_battle_02_01",
          "voiceSkill1": "madara_skill_02_06",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "madara_attack_02_03",
          "voiceDeath": "madara_menu_02"
        },
        {
          "cardVoiceId": "37",
          "cardId": "20030901",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_battle_02_02",
          "voiceSkill1": "madara_skill_02_20",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "madara_win_02_03",
          "voiceDeath": "madara_death_02_02"
        },
        {
          "cardVoiceId": "38",
          "cardId": "20030902",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_battle_02_01",
          "voiceSkill1": "obito_skill_02_07",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "obito_win_02_01",
          "voiceDeath": "obito_death_02_03"
        },
        {
          "cardVoiceId": "39",
          "cardId": "20030905",
          "dirName": "kakasi",
          "evolutionStep": "6",
          "voiceAppear": "kakasi_battle_02_01",
          "voiceSkill1": "kakasi_attack_02_02",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "kakasi_menu_05",
          "voiceDeath": "kakasi_menu_06"
        },
        {
          "cardVoiceId": "40",
          "cardId": "20030906",
          "dirName": "naruto",
          "evolutionStep": "6",
          "voiceAppear": "naruto_battle_01_01",
          "voiceSkill1": "naruto_pursuit_01_01",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "naruto_win_01_01",
          "voiceDeath": "naruto_death_01_01"
        },
        {
          "cardVoiceId": "41",
          "cardId": "20030907",
          "dirName": "sasuke",
          "evolutionStep": "6",
          "voiceAppear": "sasuke_battle_01_01",
          "voiceSkill1": "sasuke_pursuit_01_01",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "sasuke_win_01_01",
          "voiceDeath": "sasuke_death_01_01"
        },
        {
          "cardVoiceId": "42",
          "cardId": "20030908",
          "dirName": "sakura",
          "evolutionStep": "6",
          "voiceAppear": "sakura_battle_01_01",
          "voiceSkill1": "sakura_skill_01_01",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "sakura_win_01_01",
          "voiceDeath": "sakura_death_01_01"
        },
        {
          "cardVoiceId": "43",
          "cardId": "20030909",
          "dirName": "kakasi",
          "evolutionStep": "6",
          "voiceAppear": "kakasi_battle_02_01",
          "voiceSkill1": "kakasi_skill_02_02,kakasi_skill_02_01",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "kakasi_win_02_01",
          "voiceDeath": "kakasi_death_02_02"
        },
        {
          "cardVoiceId": "44",
          "cardId": "20001819",
          "dirName": "guy",
          "evolutionStep": "6",
          "voiceAppear": "guy_skill_02_07",
          "voiceSkill1": "guy_skill_02_02",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "guy_win_02_03",
          "voiceDeath": "guy_death_02_02"
        },
        {
          "cardVoiceId": "45",
          "cardId": "20030918",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_06",
          "voiceSkill1": "naruto_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_05",
          "voiceDeath": "naruto_death_02_02"
        },
        {
          "cardVoiceId": "46",
          "cardId": "20030920",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_04",
          "voiceSkill1": "sasuke_skill_02_06,sasuke_pursuit_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_05",
          "voiceDeath": "sasuke_death_02_03"
        },
        {
          "cardVoiceId": "47",
          "cardId": "20030923",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_pursuit_02_01",
          "voiceSkill1": "sasuke_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_01",
          "voiceDeath": "sasuke_death_02_01"
        },
        {
          "cardVoiceId": "48",
          "cardId": "20030924",
          "dirName": "itachi",
          "evolutionStep": "",
          "voiceAppear": "itachi_battle_02_02",
          "voiceSkill1": "itachi_skill_02_02,itachi_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "itachi_win_02_02",
          "voiceDeath": "itachi_death_02_02"
        },
        {
          "cardVoiceId": "49",
          "cardId": "20031006",
          "dirName": "minato",
          "evolutionStep": "",
          "voiceAppear": "minato_battle_02_02",
          "voiceSkill1": "minato_skill_02_09",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "minato_win_02_02",
          "voiceDeath": "minato_death_02_03"
        },
        {
          "cardVoiceId": "50",
          "cardId": "20031007",
          "dirName": "kushina",
          "evolutionStep": "",
          "voiceAppear": "kushina_battle_02_02",
          "voiceSkill1": "kushina_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kushina_win_02_02",
          "voiceDeath": "kushina_death_02_02"
        },
        {
          "cardVoiceId": "51",
          "cardId": "20031008",
          "dirName": "naruto",
          "evolutionStep": "6",
          "voiceAppear": "naruto_gacha_fix_01",
          "voiceSkill1": "naruto_pursuit_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_01",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "52",
          "cardId": "20031011",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_04",
          "voiceSkill1": "naruto_skill_01_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_gacha_fix_02",
          "voiceDeath": "naruto_death_02_02"
        },
        {
          "cardVoiceId": "53",
          "cardId": "20031018",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_pursuit_02_01",
          "voiceSkill1": "hashirama_attack_02_03",
          "voiceSkill2": "0",
          "voicePursuit": "0",
          "voiceWin": "hashirama_win_02_03",
          "voiceDeath": "hashirama_death_02_02"
        },
        {
          "cardVoiceId": "54",
          "cardId": "20031019",
          "dirName": "deidara",
          "evolutionStep": "",
          "voiceAppear": "deidara_battle_02_03",
          "voiceSkill1": "deidara_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "deidara_win_02_01",
          "voiceDeath": "deidara_death_02_03"
        },
        {
          "cardVoiceId": "55",
          "cardId": "20031020",
          "dirName": "tobi",
          "evolutionStep": "",
          "voiceAppear": "tobi_battle_02_01",
          "voiceSkill1": "tobi_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "tobi_win_02_02",
          "voiceDeath": "tobi_death_02_03"
        },
        {
          "cardVoiceId": "56",
          "cardId": "20031102",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_menu_event_01",
          "voiceSkill1": "hashirama_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hashirama_menu_04",
          "voiceDeath": "hashirama_damage_02_02"
        },
        {
          "cardVoiceId": "57",
          "cardId": "20031103",
          "dirName": "tobirama",
          "evolutionStep": "",
          "voiceAppear": "tobirama_battle_02_02",
          "voiceSkill1": "tobirama_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "tobirama_win_02_02",
          "voiceDeath": "tobirama_death_02_01"
        },
        {
          "cardVoiceId": "58",
          "cardId": "20031104",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_menu_04",
          "voiceSkill1": "madara_skill_02_16",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_win_02_02",
          "voiceDeath": "madara_death_02_01"
        },
        {
          "cardVoiceId": "59",
          "cardId": "20031113",
          "dirName": "guy",
          "evolutionStep": "",
          "voiceAppear": "guy_battle_02_04",
          "voiceSkill1": "guy_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "guy_win_02_01",
          "voiceDeath": "guy_death_02_03"
        },
        {
          "cardVoiceId": "60",
          "cardId": "20031106",
          "dirName": "jiraiya",
          "evolutionStep": "",
          "voiceAppear": "jiraiya_battle_02_03",
          "voiceSkill1": "jiraiya_damage_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "jiraiya_win_02_02",
          "voiceDeath": "jiraiya_death_02_03"
        },
        {
          "cardVoiceId": "61",
          "cardId": "20031107",
          "dirName": "sasori",
          "evolutionStep": "",
          "voiceAppear": "sasori_pursuit_02_01",
          "voiceSkill1": "sasori_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasori_win_02_02",
          "voiceDeath": "sasori_death_02_02"
        },
        {
          "cardVoiceId": "62",
          "cardId": "20031110",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_01",
          "voiceSkill1": "naruto_pursuit_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "63",
          "cardId": "20031111",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_03_02",
          "voiceSkill1": "sasuke_pursuit_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_04",
          "voiceDeath": "sasuke_death_02_01"
        },
        {
          "cardVoiceId": "64",
          "cardId": "20031114",
          "dirName": "lee",
          "evolutionStep": "",
          "voiceAppear": "lee_battle_02_02",
          "voiceSkill1": "lee_skill_02_07,lee_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "lee_win_02_02",
          "voiceDeath": "lee_death_02_02"
        },
        {
          "cardVoiceId": "65",
          "cardId": "20031115",
          "dirName": "pain",
          "evolutionStep": "",
          "voiceAppear": "pain_battle_02_01",
          "voiceSkill1": "pain_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "pain_win_02_02",
          "voiceDeath": "pain_death_02_01"
        },
        {
          "cardVoiceId": "66",
          "cardId": "20031201",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_06",
          "voiceSkill1": "naruto_skill_02_12,naruto_skill_02_23",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_skill_02_19",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "67",
          "cardId": "20031202",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_02",
          "voiceSkill1": "sasuke_skill_02_06,sasuke_skill_02_01,sasuke_skill_02_18",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_05",
          "voiceDeath": "sasuke_death_02_05"
        },
        {
          "cardVoiceId": "68",
          "cardId": "20031206",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_battle_02_06",
          "voiceSkill1": "obito_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "obito_win_02_02",
          "voiceDeath": "obito_death_02_04"
        },
        {
          "cardVoiceId": "69",
          "cardId": "20031207",
          "dirName": "kamen",
          "evolutionStep": "",
          "voiceAppear": "kamen_battle_02_01",
          "voiceSkill1": "kamen_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kamen_win_02_03",
          "voiceDeath": "kamen_death_02_02"
        },
        {
          "cardVoiceId": "70",
          "cardId": "20031208",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_battle_04_02",
          "voiceSkill1": "obito_skill_04_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "obito_win_04_01",
          "voiceDeath": "obito_death_04_02"
        },
        {
          "cardVoiceId": "71",
          "cardId": "20031209",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_battle_02_03",
          "voiceSkill1": "madara_attack_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_death_02_03",
          "voiceDeath": "madara_damage_02_01"
        },
        {
          "cardVoiceId": "72",
          "cardId": "20031210",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_01",
          "voiceSkill1": "sasuke_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_01",
          "voiceDeath": "sasuke_death_02_01"
        },
        {
          "cardVoiceId": "73",
          "cardId": "20031212",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_skill_02_17",
          "voiceSkill1": "madara_skill_02_04",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_win_02_03",
          "voiceDeath": "madara_death_02_01"
        },
        {
          "cardVoiceId": "74",
          "cardId": "20031213",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_pursuit_02_01",
          "voiceSkill1": "hashirama_attack_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hashirama_win_02_03",
          "voiceDeath": "hashirama_death_02_01"
        },
        {
          "cardVoiceId": "75",
          "cardId": "20031217",
          "dirName": "kushina",
          "evolutionStep": "",
          "voiceAppear": "kushina_battle_02_01",
          "voiceSkill1": "kushina_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kushina_win_02_03",
          "voiceDeath": "kushina_death_02_03"
        },
        {
          "cardVoiceId": "76",
          "cardId": "20031218",
          "dirName": "rin",
          "evolutionStep": "",
          "voiceAppear": "rin_battle_04_02",
          "voiceSkill1": "",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "rin_win_04_02",
          "voiceDeath": "rin_death_04_02"
        },
        {
          "cardVoiceId": "77",
          "cardId": "20040102",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_menu_03",
          "voiceSkill1": "kakasi_skill_02_04,kakasi_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_win_02_02",
          "voiceDeath": "kakasi_damage_02_01"
        },
        {
          "cardVoiceId": "78",
          "cardId": "20040103",
          "dirName": "guy",
          "evolutionStep": "",
          "voiceAppear": "guy_battle_02_01",
          "voiceSkill1": "guy_skill_02_10",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "guy_win_02_01",
          "voiceDeath": "guy_death_02_03"
        },
        {
          "cardVoiceId": "79",
          "cardId": "20040104",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_08",
          "voiceSkill1": "naruto_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_damage_02_01"
        },
        {
          "cardVoiceId": "80",
          "cardId": "20040105",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_menu_01",
          "voiceSkill1": "sasuke_attack_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_menu_02",
          "voiceDeath": "sasuke_damage_02_01"
        },
        {
          "cardVoiceId": "81",
          "cardId": "20040106",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_battle_02_01",
          "voiceSkill1": "sakura_skill_02_07",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_battle_02_06",
          "voiceDeath": "sakura_death_02_04"
        },
        {
          "cardVoiceId": "82",
          "cardId": "20040108",
          "dirName": "pain",
          "evolutionStep": "",
          "voiceAppear": "pain_battle_02_03",
          "voiceSkill1": "pain_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "pain_win_02_03",
          "voiceDeath": "pain_death_02_02"
        },
        {
          "cardVoiceId": "83",
          "cardId": "20040111",
          "dirName": "gaara",
          "evolutionStep": "",
          "voiceAppear": "gaara_battle_01_03",
          "voiceSkill1": "gaara_pursuit_01_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "gaara_win_01_03",
          "voiceDeath": "gaara_death_01_03"
        },
        {
          "cardVoiceId": "84",
          "cardId": "20040113",
          "dirName": "itachi",
          "evolutionStep": "",
          "voiceAppear": "itachi_battle_02_01",
          "voiceSkill1": "itachi_skill_02_09",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "itachi_win_02_01",
          "voiceDeath": "itachi_death_02_01"
        },
        {
          "cardVoiceId": "85",
          "cardId": "20040115",
          "dirName": "minato",
          "evolutionStep": "",
          "voiceAppear": "minato_attack_02_03",
          "voiceSkill1": "minato_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "minato_win_02_01",
          "voiceDeath": "minato_death_02_02"
        },
        {
          "cardVoiceId": "86",
          "cardId": "20040302",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_battle_02_01",
          "voiceSkill1": "kakasi_skill_02_04,kakasi_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_win_02_02",
          "voiceDeath": "kakasi_death_02_01"
        },
        {
          "cardVoiceId": "87",
          "cardId": "20040303",
          "dirName": "tsunade",
          "evolutionStep": "",
          "voiceAppear": "tsunade_battle_02_01",
          "voiceSkill1": "tsunade_skill_02_03,tsunade_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "tsunade_win_02_03",
          "voiceDeath": "tsunade_death_02_03"
        },
        {
          "cardVoiceId": "88",
          "cardId": "20040304",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_battle_02_02",
          "voiceSkill1": "sakura_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_02_02",
          "voiceDeath": "sakura_death_02_02"
        },
        {
          "cardVoiceId": "89",
          "cardId": "20040201",
          "dirName": "minato",
          "evolutionStep": "",
          "voiceAppear": "minato_battle_02_01",
          "voiceSkill1": "minato_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "minato_win_02_03",
          "voiceDeath": "minato_death_02_01"
        },
        {
          "cardVoiceId": "90",
          "cardId": "20040202",
          "dirName": "kushina",
          "evolutionStep": "",
          "voiceAppear": "kushina_battle_02_03",
          "voiceSkill1": "kushina_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kushina_win_02_01",
          "voiceDeath": "kushina_death_02_01"
        },
        {
          "cardVoiceId": "91",
          "cardId": "20040205",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_battle_02_01",
          "voiceSkill1": "madara_skill_02_11",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_win_02_02",
          "voiceDeath": "madara_death_02_02"
        },
        {
          "cardVoiceId": "92",
          "cardId": "20040207",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_battle_02_02",
          "voiceSkill1": "obito_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "obito_win_02_03",
          "voiceDeath": "obito_death_02_03"
        },
        {
          "cardVoiceId": "93",
          "cardId": "20040209",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_09",
          "voiceSkill1": "naruto_skill_02_08,naruto_skill_02_07",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "94",
          "cardId": "20040210",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_03",
          "voiceSkill1": "sasuke_skill_02_12",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_04",
          "voiceDeath": "sasuke_death_02_04"
        },
        {
          "cardVoiceId": "95",
          "cardId": "20040212",
          "dirName": "tobirama",
          "evolutionStep": "",
          "voiceAppear": "tobirama_battle_02_01",
          "voiceSkill1": "tobirama_skill_02_05,tobirama_skill_02_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "tobirama_win_02_01",
          "voiceDeath": "tobirama_death_02_03"
        },
        {
          "cardVoiceId": "96",
          "cardId": "20040213",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_01",
          "voiceSkill1": "",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_01_01",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "97",
          "cardId": "20040315",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_battle_04_02",
          "voiceSkill1": "obito_skill_04_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "obito_win_04_02",
          "voiceDeath": "obito_death_04_01"
        },
        {
          "cardVoiceId": "98",
          "cardId": "20040307",
          "dirName": "pain",
          "evolutionStep": "",
          "voiceAppear": "pain_battle_02_02",
          "voiceSkill1": "pain_pursuit_02_02,pain_pursuit_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "pain_win_02_03",
          "voiceDeath": "pain_gacha_tap_02"
        },
        {
          "cardVoiceId": "99",
          "cardId": "20040312",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_battle_02_05",
          "voiceSkill1": "sakura_skill_02_15",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_02_03",
          "voiceDeath": "sakura_death_02_04"
        },
        {
          "cardVoiceId": "100",
          "cardId": "20040310",
          "dirName": "deidara",
          "evolutionStep": "",
          "voiceAppear": "deidara_battle_02_01",
          "voiceSkill1": "deidara_skill_02_03,deidara_pursuit_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "deidara_win_02_03",
          "voiceDeath": "deidara_death_02_02"
        },
        {
          "cardVoiceId": "101",
          "cardId": "20040311",
          "dirName": "sasori",
          "evolutionStep": "",
          "voiceAppear": "sasori_battle_02_02",
          "voiceSkill1": "sasori_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasori_win_02_03",
          "voiceDeath": "sasori_death_02_02"
        },
        {
          "cardVoiceId": "102",
          "cardId": "20040402",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_menu_mission_01",
          "voiceSkill1": "madara_gacha_start_01,madara_attack_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_attack_02_03",
          "voiceDeath": "madara_menu_01"
        },
        {
          "cardVoiceId": "103",
          "cardId": "20040314",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_pursuit_02_01",
          "voiceSkill1": "",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_gacha_fix_01",
          "voiceDeath": "sasuke_death_02_01"
        },
        {
          "cardVoiceId": "104",
          "cardId": "20040407",
          "dirName": "rin",
          "evolutionStep": "",
          "voiceAppear": "rin_death_04_01",
          "voiceSkill1": "rin_damage_04_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "rin_death_04_01_01",
          "voiceDeath": "rin_death_04_02"
        },
        {
          "cardVoiceId": "105",
          "cardId": "20040404",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_battle_02_02",
          "voiceSkill1": "hashirama_attack_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hashirama_menu_shinobi_01",
          "voiceDeath": "hashirama_death_02_02"
        },
        {
          "cardVoiceId": "106",
          "cardId": "20040405",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_skill_02_09",
          "voiceSkill1": "madara_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_menu_event_01",
          "voiceDeath": "madara_death_02_02"
        },
        {
          "cardVoiceId": "107",
          "cardId": "20040415",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_pursuit_01_02",
          "voiceSkill1": "sasuke_skill_01_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_01_01",
          "voiceDeath": "sasuke_death_01_01"
        },
        {
          "cardVoiceId": "108",
          "cardId": "20040503",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_skill_03_01_01",
          "voiceSkill1": "naruto_skill_03_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_03_01",
          "voiceDeath": "naruto_death_03_01"
        },
        {
          "cardVoiceId": "109",
          "cardId": "20040504",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_03_02",
          "voiceSkill1": "sasuke_battle_03_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_03_02",
          "voiceDeath": "sasuke_death_03_01"
        },
        {
          "cardVoiceId": "110",
          "cardId": "20040505",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_skill_03_02",
          "voiceSkill1": "sakura_skill_02_07",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_03_01",
          "voiceDeath": "sakura_death_03_01"
        },
        {
          "cardVoiceId": "111",
          "cardId": "20040506",
          "dirName": "deidara",
          "evolutionStep": "",
          "voiceAppear": "deidara_battle_02_02",
          "voiceSkill1": "deidara_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "deidara_win_02_02",
          "voiceDeath": "deidara_death_02_01"
        },
        {
          "cardVoiceId": "112",
          "cardId": "20040507",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_01",
          "voiceSkill1": "sasuke_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_01",
          "voiceDeath": "sasuke_death_02_01"
        },
        {
          "cardVoiceId": "113",
          "cardId": "20040508",
          "dirName": "itachi",
          "evolutionStep": "",
          "voiceAppear": "itachi_battle_02_02",
          "voiceSkill1": "itachi_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "itachi_win_02_02",
          "voiceDeath": "itachi_death_02_01"
        },
        {
          "cardVoiceId": "114",
          "cardId": "20040509",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_menu_mission_01",
          "voiceSkill1": "madara_skill_02_18",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_attack_02_02",
          "voiceDeath": "madara_gacha_tap_01"
        },
        {
          "cardVoiceId": "115",
          "cardId": "20040511",
          "dirName": "hashirama",
          "evolutionStep": "",
          "voiceAppear": "hashirama_battle_02_01",
          "voiceSkill1": "hashirama_skill_02_11",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "hashirama_win_02_01",
          "voiceDeath": "hashirama_death_02_01"
        },
        {
          "cardVoiceId": "116",
          "cardId": "20040512",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_gacha_tap_03",
          "voiceSkill1": "madara_battle_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_attack_02_03",
          "voiceDeath": "madara_menu_02"
        },
        {
          "cardVoiceId": "117",
          "cardId": "20040513",
          "dirName": "iruka",
          "evolutionStep": "",
          "voiceAppear": "iruka_battle_02_01",
          "voiceSkill1": "iruka_skill_02_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "iruka_win_02_03",
          "voiceDeath": "iruka_death_02_02"
        },
        {
          "cardVoiceId": "118",
          "cardId": "20040517",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_12",
          "voiceSkill1": "kakasi_skill_02_24,kurama_battle_02_03,naruto_skill_02_50,naruto_skill_02_51,naruto_skill_02_52,mix_skill_02_01,mix_skill_02_02,mix_skill_02_03,naruto_skill_02_49,kurama_skill_02_01,naruto_card_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_09,kurama_win_02_02",
          "voiceDeath": "naruto_death_02_07,kurama_death_02_03"
        },
        {
          "cardVoiceId": "119",
          "cardId": "20040518",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_battle_02_17",
          "voiceSkill1": "naruto_battle_02_01,kakasi_skill_02_19,kakasi_skill_02_26,kakasi_skill_02_27,mix_skill_02_01,mix_skill_02_02,mix_skill_02_03,kakasi_skill_02_20,kakasi_card_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_win_02_04",
          "voiceDeath": "kakasi_death_02_05"
        },
        {
          "cardVoiceId": "120",
          "cardId": "20040602",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_pursuit_02_02",
          "voiceSkill1": "naruto_battle_02_09,narutoskill_02_28",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_06",
          "voiceDeath": "naruto_death_02_07"
        },
        {
          "cardVoiceId": "121",
          "cardId": "20040603",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_10",
          "voiceSkill1": "sasuke_attack_02_03,sasuke_pursui_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_09",
          "voiceDeath": "sasuke_death_02_09"
        },
        {
          "cardVoiceId": "122",
          "cardId": "20001776",
          "dirName": "naruto",
          "evolutionStep": "7",
          "voiceAppear": "naruto_battle_02_05",
          "voiceSkill1": "naruto_skill_01_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_04",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "123",
          "cardId": "20001777",
          "dirName": "sasuke",
          "evolutionStep": "7",
          "voiceAppear": "sasuke_battle_02_02",
          "voiceSkill1": "sasuke_skill_02_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_02",
          "voiceDeath": "sasuke_death_02_03"
        },
        {
          "cardVoiceId": "124",
          "cardId": "20001713",
          "dirName": "guy",
          "evolutionStep": "7",
          "voiceAppear": "guy_pursuit_02_01",
          "voiceSkill1": "guy_skill_02_18",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "guy_death_02_01",
          "voiceDeath": "guy_death_02_02"
        },
        {
          "cardVoiceId": "125",
          "cardId": "20040605",
          "dirName": "itachi",
          "evolutionStep": "",
          "voiceAppear": "itachi_battle_02_03",
          "voiceSkill1": "itachi_skill_02_10",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "itachi_skill_02_15",
          "voiceDeath": "itachi_death_02_02"
        },
        {
          "cardVoiceId": "126",
          "cardId": "20040607",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_menu_04",
          "voiceSkill1": "madara_skill_02_08,madara_attack_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_gacha_tap_03",
          "voiceDeath": "madara_menu_03"
        },
        {
          "cardVoiceId": "127",
          "cardId": "20040702",
          "dirName": "minato",
          "evolutionStep": "",
          "voiceAppear": "minato_battle_02_02",
          "voiceSkill1": "minato_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "minato_win_02_02",
          "voiceDeath": "minato_death_02_02"
        },
        {
          "cardVoiceId": "128",
          "cardId": "20040704",
          "dirName": "pain",
          "evolutionStep": "",
          "voiceAppear": "pain_skill_02_04",
          "voiceSkill1": "pain_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "pain_win_02_03",
          "voiceDeath": "pain_death_02_01"
        },
        {
          "cardVoiceId": "129",
          "cardId": "20040705",
          "dirName": "kushina",
          "evolutionStep": "",
          "voiceAppear": "kushina_pursuit_02_02",
          "voiceSkill1": "kushina_battle_02_02,minato_skill_02_10",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kushina_win_02_02",
          "voiceDeath": "kushina_death_02_02"
        },
        {
          "cardVoiceId": "130",
          "cardId": "20040706",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_skill_02_36",
          "voiceSkill1": "naruto_skill_02_29",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_battle_02_20",
          "voiceDeath": "naruto_death_02_06"
        },
         {
          "cardVoiceId": "131",
          "cardId": "20040707",
          "dirName": "kimimaro",
          "evolutionStep": "",
          "voiceAppear": "kimimaro_battle_02_03",
          "voiceSkill1": "kimimaro_skill_02_09,kimimaro_skill_02_08,kimimaro_skill_02_05",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kimimaro_win_02_02",
          "voiceDeath": "kimimaro_death_02_02"
        },
        {
          "cardVoiceId": "132",
          "cardId": "20040708",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_05",
          "voiceSkill1": "sasuke_skill_02_37",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_11",
          "voiceDeath": "sasuke_death_02_06"
        },
        {
          "cardVoiceId": "133",
          "cardId": "20040802",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_16",
          "voiceSkill1": "naruto_pursuit_02_04,sasuke_skill_02_41",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_10",
          "voiceDeath": "naruto_death_02_06"
        },
        {
          "cardVoiceId": "134",
          "cardId": "20040803",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_skill_02_30",
          "voiceSkill1": "sasuke_skill_02_41,naruto_skill_02_48",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_skill_02_40",
          "voiceDeath": "sasuke_death_02_07"
        },
        {
          "cardVoiceId": "135",
          "cardId": "20040804",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_29",
          "voiceSkill1": "naruto_skill_02_03,naruto_skill_02_39",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_menu_06",
          "voiceDeath": "naruto_death_02_05"
        },
        {
          "cardVoiceId": "136",
          "cardId": "20040805",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_gacha_fix_02",
          "voiceSkill1": "sasuke_skill_02_05,sasuke_skill_02_03",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_13",
          "voiceDeath": "sasuke_death_02_10"
        },
        {
          "cardVoiceId": "137",
          "cardId": "20040806",
          "dirName": "sakura",
          "evolutionStep": "",
          "voiceAppear": "sakura_battle_02_07",
          "voiceSkill1": "sakura_skill_02_11,sakura_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sakura_win_02_04",
          "voiceDeath": "sakura_death_02_05"
        },
        {
          "cardVoiceId": "138",
          "cardId": "20040810",
          "dirName": "madara",
          "evolutionStep": "",
          "voiceAppear": "madara_battle_02_03",
          "voiceSkill1": "madara_skill_02_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "madara_skill_02_19",
          "voiceDeath": "madara_death_02_03"
        },
        {
          "cardVoiceId": "139",
          "cardId": "20040903",
          "dirName": "guy",
          "evolutionStep": "",
          "voiceAppear": "guy_battle_02_03",
          "voiceSkill1": "guy_skill_02_16,guy_skill_02_17,guy_skill_02_18",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "guy_menu_04",
          "voiceDeath": "guy_death_02_03"
        },
        {
          "cardVoiceId": "140",
          "cardId": "20040904",
          "dirName": "gaara",
          "evolutionStep": "",
          "voiceAppear": "gaara_battle_02_03",
          "voiceSkill1": "gaara_battle_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "gaara_win_02_01",
          "voiceDeath": "gaara_death_02_03"
        },
        {
          "cardVoiceId": "141",
          "cardId": "20040905",
          "dirName": "obito",
          "evolutionStep": "",
          "voiceAppear": "obito_skill_04_05",
          "voiceSkill1": "obito_skill_04_06",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "obito_damage_04_01",
          "voiceDeath": "obito_damage_04_02"
        },
        {
          "cardVoiceId": "8001",
          "cardId": "80000001",
          "dirName": "naruto",
          "evolutionStep": "",
          "voiceAppear": "naruto_battle_02_10",
          "voiceSkill1": "naruto_skill_02_12,naruto_skill_02_21,naruto_skill_02_22",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_06",
          "voiceDeath": "naruto_death_02_03"
        },
        {
          "cardVoiceId": "142",
          "cardId": "20030503",
          "dirName": "naruto",
          "evolutionStep": "7",
          "voiceAppear": "naruto_battle_02_03",
          "voiceSkill1": "naruto_skill_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "naruto_win_02_03",
          "voiceDeath": "naruto_death_02_01"
        },
        {
          "cardVoiceId": "143",
          "cardId": "20001848",
          "dirName": "sasuke",
          "evolutionStep": "7",
          "voiceAppear": "sasuke_battle_03_02",
          "voiceSkill1": "sasuke_battle_03_01",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_03_01",
          "voiceDeath": "sasuke_death_03_02"
        },
        {
          "cardVoiceId": "144",
          "cardId": "20040906",
          "dirName": "kakasi",
          "evolutionStep": "",
          "voiceAppear": "kakasi_battle_02_06",
          "voiceSkill1": "kakasi_skill_02_05,kakasi_pursuit_02_02",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "kakasi_skill_02_13",
          "voiceDeath": "kakasi_death_02_04"
        },
        {
          "cardVoiceId": "8002",
          "cardId": "80000002",
          "dirName": "sasuke",
          "evolutionStep": "",
          "voiceAppear": "sasuke_battle_02_04",
          "voiceSkill1": "sasuke_skill_02_09,sasuke_skill_02_10,sasuke_skill_02_07,sasuke_skill_02_08",
          "voiceSkill2": "",
          "voicePursuit": "",
          "voiceWin": "sasuke_win_02_03",
          "voiceDeath": "sasuke_death_02_04"
        }
]
