window.gear=[
    [1, "Genin Kunai", "Stats", "ATK +20%", "None", "None"],
    [2, "Chunin Kunai", "Stats", "ATK +30%", "None", "None"],
    [3, "Genin Socks", "Stats", "SPD +20%", "None", "None"],
    [4, "Chunin Socks", "Stats", "SPD +30%", "None", "None"],
    [5, "Genin Headband", "Chakra", "Chakra Cost Reduced by 6%", "None", "None"],
    [6, "Chunin  Headband", "Chakra", "Chakra Cost Reduced by 9%", "None", "None"],
    [7, "Genin Glove Hooks", "Stats", "CRIT Chance +10%", "None", "None"],
    [8, "Chunin Glove Hooks", "Stats", "CRIT Chance +20%", "None", "None"],
    [9, "Genin Vest", "Stats", "DEF +20%", "None", "None"],
    [10, "Chunin Vest", "Stats", "DEF +30%", "None", "None"],
    [11, "Genin Jacket", "Stats", "HP +10%", "None", "None"],
    [12, "Chunin Jacket", "Stats", "HP +16%", "None", "None"],
    [13, "Genin Ninja Star", "Skill", "Weapon Type damage +20%", "None", "None"],
    [14, "Chunin Ninja Star", "Skill", "Weapon Type damage +30%", "None", "None"],
    [15, "Headband of Fortitude", "Stats", "DEF and HP +20%", "None", "None"],
    [16, "White Amulet", "Resistance", "Lessens chance of Confusion", "None", "None"],
    [17, "Orange Amulet", "Resistance", "Lessens chance of Sealed", "None", "None"],
    [18, "Bloodstained Katana", "Resistance", "After each action recover 2% HP", "None", "None"],
    [19, "Purple Amulet", "Resistance", "Lessens chance of Poison", "None", "None"],
    [20, "Yellow Amulet", "Resistance", "Lessens chance of Paralyzed", "None", "None"],
    [21, "Power Pills", "Stats", "For the first 3 turns ATK +30%", "None", "None"],
    [22, "Scarlet Kunai", "Skill", "Fire Type Skill damage +20%", "None", "None"],
    [23, "Amber Kunai", "Skill", "Taijutsu Type Skill damage +20%", "None", "None"],
    [24, "Sky Blue Kunai", "Skill", "Unique Type Skill damage +20%", "None", "None"],
    [25, "Snow White Kunai", "Skill", "Secret Type Skill damage +20%", "None", "None"],
    [26, "Jet-Black Kunai", "Skill", "Summoning Type Skill damage +20%", "None", "None"],
    [27, "Genin Smoke Ball", "Stats", "Evasion +10%", "None", "None"],
    [28, "Chunin Smoke Ball", "Stats", "Evasion +16%", "None", "None"],
    [29, "Chunin Smoke Ball", "Stats", "Evasion +16%", "None", "None"],
    [30, "Pills of Herculean Strength", "Stats", "For the first 3 turns ATK +50%", "None", "None"],
    [31, "Pills of Patience", "Stats", "For the first 3 turns DEF +50%", "None", "None"],
    [32, "Protection Vest - Lightning", "Resistance", "Reduce Lightning Type Damage Taken", "None", "None"],
    [33, "Protection Vest - Water", "Resistance", "Reduce Water Type Damage Taken", "None", "None"],
    [34, "Protection Vest - Wind", "Resistance", "Reduce Wind Type Damage Taken", "None", "None"],
    [35, "Protection Vest - Earth", "Resistance", "Reduce Earth Type Damage Taken", "None", "None"],
    [36, "Katana - Bright Yellow", "Skill", "Wood Style Type Damage +20%", "None", "None"],
    [37, "Katana - Purple Electricity", "Skill", "Lightning Style Type Damage +20%", "None", "None"],
    [38, "Focus Band", "Chakra", "Chakra restored 5% after every action", "None", "None"],
    [39, "Jade Jacket", "Resistance", "Lessens chance of getting Poisoned", "None", "None"],
    [40, "Immobility Jacket", "Resistance", "Lessens chance of getting Paralyzed", "None", "None"],
    [41, "Crimson Jacket", "Resistance", "Byakugan type damage decreased", "None", "None"],
    [42, "Adamantite Jacket", "Resistance", "Taijutsu type damage decreased", "None", "None"],
    [43, "Jonin Kunai", "Stats", "ATK +40%", "None", "None"],
    [44, "Jonin Vest", "Stats", "DEF +40%", "None", "None"],
    [45, "Infallible Katana", "Additional Effect", "Normal Attacks Can't Miss", "None", "None"],
    [46, "Makeout Paradise", "Skill", "Summoning Type Jutsu Damage +30%", "None", "None"],
    [47, "Gai's Tracksuit", "Resistance", "Reduced Damage from Taijutsu and Weapon Type Jutsu, HP +10%", "None", "None"],
    [48, "Gai's Tracksuit", "Resistance", "Reduced Damage from Taijutsu and Weapon Type Jutsu, HP +10%", "None", "None"],
    [49, "Special Frog Suit", "Resistance", "Reduced Damage from Fire and Water Style Type Jutsu, HP +10%", "None", "None"],
    [50, "Sword of Kusanagi", "Stats", "ATK +60%", "None", "None"],
    [51, "Protection Vest - Wood", "Resistance", "Wood type damage decreased", "None", "None"],
    [52, "Gale Socks", "Stats", "SPD +50", "None", "None"],
    [53, "Awakening Pill", "Resistance", "Maximum HP +10%. For the first 2 rounds, immune to negative effects", "None", "None"],
    [54, "Three Color Pills", "Stats", "For the first 3 turns, ATK and SPD +20%, DEF -20%", "None", "None"],
    [55, "Beach Umbrella", "Skill", "Wind type damage increased +20%", "None", "None"],
    [56, "Luxury sun oil", "Resistance", "DEF +20%. For the first 2 turns, immune to water type damage.", "None", "None"],
    [57, "Missing Nin's Forehead Protector", "Chakra", "Maximum HP -20%, Chakra cost -12%", "None", "None"],
    [58, "Akatsuki Cloak", "Resistance", "Immune to bind status, Maximum HP +24%, SPD -20%", "None", "None"],
    [59, "Detoxification injection", "Resistance", "ATK -10%. For the first 5 turns, immune to poison status", "None", "None"],
    [60, "Uchiha Blade", "Skill", "Sharingan Jutsu Damage +20%", "None", "None"],
    [61, "Rinnegan Kunai", "Skill", "Rinnegan Jutsu Damage +30%", "None", "None"],
    [62, "Byakugan Kunai", "Skill", "Byakugan Damage +30%", "None", "None"],
    [63, "Water Kunai", "Skill", "Water Style Skill Damage +30%", "None", "None"],
    [64, "Magnetic Kunai", "Skill", "Magnetic Type Skill Damage +30%", "None", "None"],
    [65, "Medical Kunai", "Skill", "Medical Ninjutsu Skill Damage +30%", "None", "None"],
    [66, "Doctor's Ointment", "Skill", "Increase Amount of Health that Skills Restore, SPD -20%", "None", "None"],
    [67, "Vitality Bandage", "Stats", "HP +2400", "None", "None"],
    [68, "Suntetsu of Fighting Spirit", "Stats", "ATK +5000", "None", "None"],
    [69, "Robust Jacket", "Stats", "DEF +5000", "None", "None"],
    [70, "Ninjatō of Sucking Blood", "Additional Effect", "Recover 5% of Normal Attack Damage in HP", "None", "None"],
    [71, "Sai's picture book", "Resistance", "Greatly Reduce Chance of Getting Paralysed, HP -10%", "None", "None"],
    [72, "Customized Kunai", "Skill", "Space Time Jutsu Damage +20%, SPD +30%", "None", "None"],
    [73, "Three Blade Scythe", "Stats", "ATK +100%, HP -30%", "None", "None"],
    [74, "Haku's Mask", "Stats", "ATK +40%, SPD +40%, HP -40%", "None", "None"],
    [75, "Zabuza's Sword", "Stats", "ATK +40%, Water and Unique type damage +20%", "None", "None"],
    [76, "Lightning Blade", "Stats", "ATK +40%, Lightning Style Damage +20%", "None", "None"],
    [77, "ANBU Mask", "Stats", "SPD +40%, Chakra cost -5%", "None", "None"],
    [78, "Hiruko", "Stats", "HP +4000, DEF +5000 and SPD -30%", "None", "None"],
    [79, "Zero", "Chakra", "After Each Action Recover 7% Chakra, Rinnegan Damage +7%", "None", "None"],
    [80, "Tsunade's Necklace", "Chakra", "Chakra cost reduced by 15%. At the end of each action low chance to restore 20% HP", "None", "None"],
    [81, "Long Sword - Samehada", "Stats", "ATK + 20%, Water type damage +20%, Chance to recover 3000 HP after attack", "None", "None"],
    [82, "Recognition Bill", "Stats", "DEF, SPD and ATK +30%", "None", "None"],
    [83, "Goggles", "Skill", "Wind Style Jutsu Damage +20%, ATK +20%", "None", "None"],
    [84, "Taka Robe", "Stats", "Blaze Style Damage +40%, HP +40%", "None", "None"],
    [85, "Wind Shuriken", "Stats", "For the First 5 Turns ATK +150%", "None", "None"],
    [86, "Hiruzen's Helmet", "Additional Effect", "When Damaged, Chance to Recover 5% Chakra", "None", "None"],
    [87, "Battle Bow", "Skill", "Secret Type Jutsu Damage +30%, ATK +10% (for 5 turns)", "None", "None"],
    [88, "Kazekage's Hat", "Skill", "Unique Jutsu Damage +30%, Max HP +20%", "None", "None"],
    [89, "Jiraiya's Forehead Protector", "Chakra", "Chakra Consumption decreased by 9%, Summoning type skill damage +20%", "None", "None"],
    [90, "Ino's Chocolate", "Additional Effect", "DEF +20%. After each action, Recover 3% Chakra", "None", "None"],
    [91, "Sakura's Chocolate", "Additional Effect", "ATK +20%. After each action, HP +3%.", "None", "None"],
    [92, "Hinata's Chocolate", "Additional Effect", "SPD +20%. After each action, HP +3%.", "None", "None"],
    [93, "Special Chocolate", "Additional Effect", "After Each Turn Recover 5% HP and Chakra", "None", "None"],
    [94, "Nine Tails' Chakra", "Chakra", "For the First 3 Turns Chakra Cost Reduced by 20%", "For the First 3 Turns Chakra Cost Reduced by 99%", "Kurama Link Mode Naruto Uzumaki Units, Minato Namikaze"],
    [95, "Minato's Kunai (Ranking Event)", "Skill", "Space Time Jutsu Damage +30%, SPD +40%", "Space Time Jutsu Damage +50%, SPD +40%, Immune to status", "All Minato Namikaze Units"],
    [96, "Exclusive Frypan", "Stats", "ATK +80%", "ATK +80%. While HP is Above 70% ATK and DEF +100%", "All Kushina Uzumaki Units"],
    [97, "Rose Bouquet", "Skill", "Sharingan Damage +30%", "Sharingan Damage +60%, After Each Action HP and Chakra +10%", "Itachi Uchiha"],
    [98, "Jet-Black Suit", "Resistance", "Incoming Sharingan Damage reduced, Sharingan Damage +10%", "Incoming Sharingan Damage Halved, Sharingan Damage +20%, Immune to Seal", "All Itachi Uchiha Units (Except Itachi Uchiha ANBU)"],
    [99, "Moon-White Suit", "Resistance", "Incoming Secret Skill Damage reduced. Secret Damage +10%", "Incoming Secret Skill Damage Halved, Secret Damage +20%, Immune to Paralysis", "All Deidara Units"],
    [100, "Blueish-Purple Suit", "Resistance", "Incoming Weapon Damage reduced, Weapon Damage +10%", "Incoming Weapon Damage Halved, Weapon skill Damage +20%, Immune to Poison", "All Sasori Units"],
    [101, "Zero", "Chakra", "Gain 10% Chakra After Each Action, Rinnegan Jutsu Damage +10%", "Gain 10% Chakra and HP After Each Action, Rinnegan Jutsu Damage +50%", "All Pain Units"],
    [102, "Makeout Tactics", "Skill", "Lightning Style & Sharingan Damage +20%, Max HP +20%", "Lightning Style & Sharingan Damage +50%, Max HP +40%", "All Kakashi Hatake Units"],
    [102, "Sage Scroll", "Skill", "Max HP +30%, Sage Jutsu Damage +40%", "Max HP and ATK +40%, Sage Jutsu Damage +100%", "All Naruto Uzumaki Units"],
    [103, "Temari's Fan", "Skill", "Wind type damage +30%, SPD +10%", "Skill type damage +70%, SPD +20%, Incoming Lightning type damage halved", "All Temari Units"],
    [104, "Mizukage's Hat", "Skill", "Water and Fire Style Damage +20%. Chance to be immune to debuffs", "Lava and Boil Style Jutsu Damage +70%, Immune to debuffs", "All Mei Terumi Units"],
    [105, "Sasuke's Waist Clasp", "Resistance", "Incoming Sharingan damage halved", "Immune to Sharingan damage. After each action, HP and Chakra recovered 10%", "Sasuke Uchiha"],
    [106, "Sasuke's Chidori-Sword", "Stats", "ATK and Sharingan damage +30%", "ATK and Sharingan damage +100%", "Sasuke Uchiha"],
    [107, "Sakura's Gloves", "Stats", "ATK and Taijutsu type skill Damage +30%", "ATK and Taijutsu type skill Damage +80%", "All Sakura Haruno Units"],
    [108, "Poison Disabling Medicine", "Resistance", "Poison/Toxic effect duration halved", "Immune to Poison/Toxic. Chakra cost -10%. Medical ninjutsu HP recovery +60%.", "All Sakura Haruno Units"],
    [109, "White Fang", "Stats", "ATK +40%, SPD +20%", "ATK +80%, SPD +40%", "All Young Kakashi Hatake Units"],
    [110, "Obito's Goggles", "Additional Effect", "Reduced damage from Sharingan Jutsu & HP +10%", "Receive half damage from Sharingan Jutsu, HP & DEF +40%", "All Young Obito Uchiha Units"],
    [111, "Medical Pack", "Skill", "Effect of Recovery skills increased by 20%", "Effect of Recovery Skills +60%, HP and DEF increased by 5000", "All Rin Nohara Units"],
    [112, "Medical Pack", "Skill", "Effect of Recovery skills increased by 20%", "Effect of Recovery Skills +60%, HP and DEF increased by 5000", "All Rin Nohara Units"],
    [113, "Team Minato's Backpack", "Resistance", "Reduced Damage from Fire, Wind and Lightning Stlye Jutsu, SPD -30%", "Half Damage from Fire, Wind and Lightning Stlye Jutsu", "Team Minato: Young Kakashi & Obito, Rin Nohara, and Jonin Minato"],
    [114, "Mazo Stakes", "Stats", "ATK and DEF +40%", "ATK and DEF +70%, Chakra Cost Reduced by 15%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
    [115, "Battle Mask", "Skill", "Fire Style and Sharingan Damage +20%", "HP +40%, Jutsu Damage +70%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
    [116, "Heaven Scroll", "Additional Effect", "When damaged, chance to recover chakra +5%", "When damaged chance to recover chakra 100%, HP +50%, and Skill Damage +30%", "Pre-Shippuden Team 7: (Naruto, Sasuke, & Sakura) and all Anko Mitarashi units"],
    [117, "Earth Scroll", "Additional Effect", "When damaged, chance to recover HP +5%", "When damaged chance to recover HP 100%, Chakra +50%, and Skill Damage +30%", "All Zaku, Dosu, & Kin Units, Adult Orochimaru (Except Sannin-era)"],
    [118, "Sasuke's Shuriken", "Stats", "ATK +60%, SPD +10%", "ATK +100%, SPD +30%, Fire type damage +50%", "Pre-Shippuden Sasuke Uchiha Units"],
    [119, "Sage Horn", "Skill", "Sage Type Jutsu and HP +10%", "Sage Type Jutsu and HP +70%", "Sage Mode Kabuto Yakushi Units"],
    [120, "Kabuto's Glasses", "Resistance", "Genjutsu/Confusion status halved", "Immune to negative effects, Attack and Defense +70%", "All Kabuto Yakushi Units"],
    [121, "Sasuke's Bow", "Skill", "Lightning Style Jutsu Damage and ATK +10%", "Lightning Style Jutsu Damage and ATK +60%", "All Sasuke Uchiha Units"],
    [122, "Itachi's Crow", "Additional Effect", "Regenerate 10% Chakra after an Action, Sharingan Damage +10%", "Regenerate 10% Chakra and HP after an Action, Sharingan Damage +60%", "All Itachi Uchiha Units"],
    [123, "Waist Clasp of the Sound Five", "Resistance", "Chance of falling under the sealed status is halved", "Immunity to Sealed and Confusion statuses. HP and DEF increased by 70%", "Sound Five (Jirobo, Tayuya, Sakon/Ukon, and Kidomaru, & Kimimaro Kaguya) Units"],
    [124, "Tayuya's Flute", "Skill", "ATK and SPD +20%, Genjutsu Skill Damage +20%", "ATK and SPD +50%, Genjutsu Skill Damage +100%", "All Tayuya Units"],
    [125, "Kamatari's Lantern", "Additional Effect", "Regenerate 5% Chakra after an Action, Wind Style Jutsu Damage +10%", "Regenerate 15% Chakra after an Action, All Jutsu's Damage +30%", "All Temari Units"],
    [125, "Kunai and Paper Bomb", "Stats", "HP and ATK +40%", "HP and ATK +80%, Secret Type Jutsu Damage +60%", "All Shikamaru Nara Units"],
    [126, "Madara's Fan", "Skill", "Fire Style and Rinnegan Jutsu Damage +20%", "All Jutsu Damage and ATK +60%", "All Madara Uchiha Units"],
    [127, "Hashirama's Cells", "Additional Effect", "Chance to grant immunity to skills, but -15% HP per turn", "+50% HP, greater chance of granting immunity to skills", "All Madara Uchiha Units"],
    [128, "Junk Food", "Additional Effect", "Max HP +15%", "None", "None"],
    [129, "Gamakichi Netsuke", "Additional Effect", "Reduced Damage from Fire, Sharingan and Lightning Style Jutsu", "Half Damage from Fire, Sharingan and Lightning Style Jutsu, Summoning jutsu damage+100%", "All Naruto Uzumaki Units"],
    [130, "Aoda Netsuke", "Additional Effect", "Reduced Damage from Taijutsu, SPD +20%", "Taijutsu Damage halved, SPD +40%, Summoning jutsu damage +80%", "All Sasuke Uchiha Units"],
    [131, "Katsuyu Netsuke", "Additional Effect", "Reduced Damage from Wind and Sage Jutsu", "Reduced damage from all skills. Immune to debuffs.", "All Sakura Haruno Units"],
    [132, "Pakkun Netsuke", "Additional Effect", "After Each Turn Recover 5% HP & Chakra", "After Each Turn Recover 10% HP and Chakra, Skill Damage +50%", "All Kakashi Hatake Units"],
    [133, "Inoshikacho Piercing (Ino)", "Stats", "HP and SPD +20%", "HP & SPD +50%, Recovery skills increase recovery +50%", "Shippuden-era Ino Yamanaka Units"],
    [134, "Inoshikacho Piercing (Shika)", "Stats", "HP and DEF +20%", "HP & DEF + 50%, Weaknesses are disabled", "Shippuden-era Shikamaru Nara Units"],
    [135, "Inoshikacho Piercing (Cho)", "Stats", "HP and ATK +20%", "HP, ATK, and Secret type skill damage +50%", "Shippuden-era Choji Akimichi Units"],
    [136, "Bingo Book", "Skill", "Wind Style Skill Damage +20%", "HP & ATK +30%, All Skill type damage +80%", "All Kakuzu Units"],
    [137, "Kakuzu's Ryo", "Additional Effect", "Money gained from missions +20%", "Money gained from missions +20%, ATK & DEF +50%", "All Kakuzu Units"],
    [138, "Summoning Scroll", "Skill", "Summoning type skill damage +20%, HP & ATK + 20%", "Summoning type skill damage +60%, HP & ATK + 40%", "Pre-Shippuden Kakashi Hatake Units"],
    [139, "Executioner's Blade", "Stats", "HP & ATK +20%, Unique skill type damage +30%", "HP, ATK, & All Skill type damage +50%", "All Zabuza Momochi Units"],
    [140, "Senbon", "Stats", "ATK & SPD +20%. Water Type skill damage +30%", "ATK, SPD, and All skill type damage +50%", "All Haku Units"],
    [141, "Hokage Necklace", "Chakra", "Chakra consumption reduced by 10%. Recovery skills have a bonus 10% recovery", "Chakra Consumption reduced by 25%. All damaging and recovery skills have a 60% boost.", "All Adult Tsunade and Hashirama Senju Units"],
    [142, "Sannin: Jiraiya's Forehead Protector", "Chakra", "Chakra consumption reduced by 5%. Genjutsu and Summoning Skill Damage increased by 20%", "Chakra Consumption reduced by 20%. All Skill damage increased by 80%.", "All Adult Jiraiya Units"],
    [143, "Deidara's Scope", "Skill", "Secret Type Jutsu Damage +20%, SPD +20%", "Secret Type Jutsu Damage +50%, SPD +50%", "All Deidara Units"],
    [144, "Gaara's Sand Gourd", "Stats", "DEF +20%, Unique Type Damage +20%", "ATK & DEF +50%, Unique type Damage +50%", "All Shippuden Gaara Units"],
    [145, "Hashirama's Armor", "Stats", "Maximum HP & DEF +30%", "Maximum HP & DEF +50%. HP recovered by 15% after each action.", "All Hashirama Senju Units"],
    [146, "Tobirama's Forehead Protector", "Chakra", "Chakra consumption decreased by 7%. Slight chance to dodge skills.", "Chakra consumption decreased by 20%. Chance to dodge skills.", "All Tobirama Senju Units"],
    [147, "Hiruzen's Shuriken", "Stats", "ATK +80%", "ATK +120%. Skill Damage +30%", "All Hiruzen Senju Units"],
    [148, "Obito's Truth-Seeking Ball", "Additional Effect", "All Skill type damage +40%, Chakra recovery amount halved", "All skill type damage +70%, great chance of skill avoidance", "All Ten-Tails Obito Uchiha Units"],
    [149, "Obito's Staff", "Stats", "ATK & SPD +50%, HP reduced by 30% after every action", "ATK & DEF + 80%, SPD +40%", "All Ten-Tails Obito Uchiha Units"],
    [150, "Anniversary Forehead Protector", "Chakra", "Chakra Consumption reduced by 5%", "Chakra consumption reduced by 15%. ATK and SPD +30%", "All Sakura Haruno Units"],

]












