window.gear=[
    [1, "Genin Kunai", "Stats", "ATK +20%", "None", "None"],
    [2, "Chunin Kunai", "Stats", "ATK +30%", "None", "None"],
    [3, "Genin Socks", "Stats", "SPD +20%", "None", "None"],
    [4, "Chunin Socks", "Stats", "SPD +30%", "None", "None"],
    [5, "Genin Headband", "Chakra", "Chakra Cost Reduced by 6%", "None", "None"],
    [6, "Chunin  Headband", "Chakra", "Chakra Cost Reduced by 9%", "None", "None"],
    [7, "Genin Glove Hooks", "Stats", "CRIT Chance +10%", "None", "None"],
    [8, "Chunin Glove Hooks", "Stats", "CRIT Chance +20%", "None", "None"],
    [9, "Genin Vest", "Stats", "DEF +20%", "None", "None"],
    [10, "Chunin Vest", "Stats", "DEF +30%", "None", "None"],
    [11, "Genin Jacket", "Stats", "HP +10%", "None", "None"],
    [12, "Chunin Jacket", "Stats", "HP +16%", "None", "None"],
    [13, "Genin Ninja Star", "Skill", "Weapon Type damage +20%", "None", "None"],
    [14, "Chunin Ninja Star", "Skill", "Weapon Type damage +30%", "None", "None"],
    [15, "Headband of Fortitude", "Stats", "DEF and HP +20%", "None", "None"],
    [16, "White Amulet", "Resistance", "Lessens chance of Confusion", "None", "None"],
    [17, "Orange Amulet", "Resistance", "Lessens chance of Sealed", "None", "None"],
    [18, "Bloodstained Katana", "Resistance", "After each action recover 2% HP", "None", "None"],
    [19, "Purple Amulet", "Resistance", "Lessens chance of Poison", "None", "None"],
    [20, "Yellow Amulet", "Resistance", "Lessens chance of Paralyzed", "None", "None"],
    [21, "Power Pills", "Stats", "For the first 3 turns ATK +30%", "None", "None"],
    [22, "Scarlet Kunai", "Skill", "Fire Type Skill damage +20%", "None", "None"],
    [23, "Amber Kunai", "Skill", "Taijutsu Type Skill damage +20%", "None", "None"],
    [24, "Sky Blue Kunai", "Skill", "Unique Type Skill damage +20%", "None", "None"],
    [25, "Snow White Kunai", "Skill", "Secret Type Skill damage +20%", "None", "None"],
    [26, "Jet-Black Kunai", "Skill", "Summoning Type Skill damage +20%", "None", "None"],
    [27, "Genin Smoke Ball", "Stats", "Evasion +10%", "None", "None"],
    [28, "Chunin Smoke Ball", "Stats", "Evasion +16%", "None", "None"],
    [29, "Chunin Smoke Ball", "Stats", "Evasion +16%", "None", "None"],
    [30, "Pills of Herculean Strength", "Stats", "For the first 3 turns ATK +50%", "None", "None"],
    [31, "Pills of Patience", "Stats", "For the first 3 turns DEF +50%", "None", "None"],
    [32, "Protection Vest - Lightning", "Resistance", "Reduce Lightning Type Damage Taken", "None", "None"],
    [33, "Protection Vest - Water", "Resistance", "Reduce Water Type Damage Taken", "None", "None"],
    [34, "Protection Vest - Wind", "Resistance", "Reduce Wind Type Damage Taken", "None", "None"],
    [35, "Protection Vest - Earth", "Resistance", "Reduce Earth Type Damage Taken", "None", "None"],
    [36, "Katana - Bright Yellow", "Skill", "Wood Style Type Damage +20%", "None", "None"],
    [37, "Katana - Purple Electricity", "Skill", "Lightning Style Type Damage +20%", "None", "None"],
    [38, "Focus Band", "Chakra", "Chakra restored 5% after every action", "None", "None"],
    [39, "Jade Jacket", "Resistance", "Lessens chance of getting Poisoned", "None", "None"],
    [40, "Immobility Jacket", "Resistance", "Lessens chance of getting Paralyzed", "None", "None"],
    [41, "Crimson Jacket", "Resistance", "Byakugan type damage decreased", "None", "None"],
    [42, "Adamantite Jacket", "Resistance", "Taijutsu type damage decreased", "None", "None"],
    [43, "Jonin Kunai", "Stats", "ATK +40%", "None", "None"],
    [44, "Jonin Vest", "Stats", "DEF +40%", "None", "None"],
    [45, "Infallible Katana", "Additional Effect", "Normal Attacks Can't Miss", "None", "None"],
    [46, "Makeout Paradise", "Skill", "Summoning Type Jutsu Damage +30%", "None", "None"],
    [47, "Gai's Tracksuit", "Resistance", "Reduced Damage from Taijutsu and Weapon Type Jutsu, HP +10%", "None", "None"],
    [48, "Gai's Tracksuit", "Resistance", "Reduced Damage from Taijutsu and Weapon Type Jutsu, HP +10%", "None", "None"],
    [49, "Special Frog Suit", "Resistance", "Reduced Damage from Fire and Water Style Type Jutsu, HP +10%", "None", "None"],
    [50, "Sword of Kusanagi", "Stats", "ATK +60%", "None", "None"],
    [51, "Protection Vest - Wood", "Resistance", "Wood type damage decreased", "None", "None"],
    [52, "Gale Socks", "Stats", "SPD +50", "None", "None"],
    [53, "Awakening Pill", "Resistance", "Maximum HP +10%. For the first 2 rounds, immune to negative effects", "None", "None"],
    [54, "Three Color Pills", "Stats", "For the first 3 turns, ATK and SPD +20%, DEF -20%", "None", "None"],
    [55, "Beach Umbrella", "Skill", "Wind type damage increased +20%", "None", "None"],
    [56, "Luxury sun oil", "Resistance", "DEF +20%. For the first 2 turns, immune to water type damage.", "None", "None"],
    [57, "Missing Nin's Forehead Protector", "Chakra", "Maximum HP -20%, Chakra cost -12%", "None", "None"],
    [58, "Akatsuki Cloak", "Resistance", "Immune to bind status, Maximum HP +24%, SPD -20%", "None", "None"],
    [59, "Detoxification injection", "Resistance", "ATK -10%. For the first 5 turns, immune to poison status", "None", "None"],
    [60, "Uchiha Blade", "Skill", "Sharingan Jutsu Damage +20%", "None", "None"],
    [61, "Rinnegan Kunai", "Skill", "Rinnegan Jutsu Damage +30%", "None", "None"],
    [62, "Byakugan Kunai", "Skill", "Byakugan Damage +30%", "None", "None"],
    [63, "Water Kunai", "Skill", "Water Style Skill Damage +30%", "None", "None"],
    [64, "Magnetic Kunai", "Skill", "Magnetic Type Skill Damage +30%", "None", "None"],
    [65, "Medical Kunai", "Skill", "Medical Ninjutsu Skill Damage +30%", "None", "None"],
    [66, "Doctor's Ointment", "Skill", "Increase Amount of Health that Skills Restore, SPD -20%", "None", "None"],
    [67, "Vitality Bandage", "Stats", "HP +2400", "None", "None"],
    [68, "Suntetsu of Fighting Spirit", "Stats", "ATK +5000", "None", "None"],
    [69, "Robust Jacket", "Stats", "DEF +5000", "None", "None"],
    [70, "Ninjatō of Sucking Blood", "Additional Effect", "Recover 5% of Normal Attack Damage in HP", "None", "None"],
    [71, "Sai's picture book", "Resistance", "Greatly Reduce Chance of Getting Paralysed, HP -10%", "None", "None"],
    [72, "Customized Kunai", "Skill", "Space Time Jutsu Damage +20%, SPD +30%", "None", "None"],
    [73, "Three Blade Scythe", "Stats", "ATK +100%, HP -30%", "None", "None"],
    [74, "Haku's Mask", "Stats", "ATK +40%, SPD +40%, HP -40%", "None", "None"],
    [75, "Zabuza's Sword", "Stats", "ATK +40%, Water and Unique type damage +20%", "None", "None"],
    [76, "Lightning Blade", "Stats", "ATK +40%, Lightning Style Damage +20%", "None", "None"],
    [77, "ANBU Mask", "Stats", "SPD +40%, Chakra cost -5%", "None", "None"],
    [78, "Hiruko", "Stats", "HP +4000, DEF +5000 and SPD -30%", "None", "None"],
    [79, "Zero", "Chakra", "After Each Action Recover 7% Chakra, Rinnegan Damage +7%", "None", "None"],
    [80, "Tsunade's Necklace", "Chakra", "Chakra cost reduced by 15%. At the end of each action low chance to restore 20% HP", "None", "None"],
    [81, "Long Sword - Samehada", "Stats", "ATK + 20%, Water type damage +20%, Chance to recover 3000 HP after attack", "None", "None"],
    [82, "Recognition Bill", "Stats", "DEF, SPD and ATK +30%", "None", "None"],
    [83, "Goggles", "Skill", "Wind Style Jutsu Damage +20%, ATK +20%", "None", "None"],
    [84, "Taka Robe", "Stats", "Blaze Style Damage +40%, HP +40%", "None", "None"],
    [85, "Wind Shuriken", "Stats", "For the First 5 Turns ATK +150%", "None", "None"],
    [86, "Hiruzen's Helmet", "Additional Effect", "When Damaged, Chance to Recover 5% Chakra", "None", "None"],
    [87, "Battle Bow", "Skill", "Secret Type Jutsu Damage +30%, ATK +10% (for 5 turns)", "None", "None"],
    [88, "Kazekage's Hat", "Skill", "Unique Jutsu Damage +30%, Max HP +20%", "None", "None"],
    [89, "Jiraiya's Forehead Protector", "Chakra", "Chakra Consumption decreased by 9%, Summoning type skill damage +20%", "None", "None"],
    [90, "Ino's Chocolate", "Additional Effect", "DEF +20%. After each action, Recover 3% Chakra", "None", "None"],
    [91, "Sakura's Chocolate", "Additional Effect", "ATK +20%. After each action, HP +3%.", "None", "None"],
    [92, "Hinata's Chocolate", "Additional Effect", "SPD +20%. After each action, HP +3%.", "None", "None"],
    [93, "Special Chocolate", "Additional Effect", "After Each Turn Recover 5% HP and Chakra", "None", "None"],
    [94, "Nine Tails' Chakra", "Chakra", "For the First 3 Turns Chakra Cost Reduced by 20%", "For the First 3 Turns Chakra Cost Reduced by 99%", "Kurama Link Mode Naruto Uzumaki Units, Minato Namikaze"],
    [95, "Minato's Kunai (Ranking Event)", "Skill", "Space Time Jutsu Damage +30%, SPD +40%", "Space Time Jutsu Damage +50%, SPD +40%, Immune to status", "All Minato Namikaze Units"],
    [96, "Exclusive Frypan", "Stats", "ATK +80%", "ATK +80%. While HP is Above 70% ATK and DEF +100%", "All Kushina Uzumaki Units"],
    [97, "Rose Bouquet", "Skill", "Sharingan Damage +30%", "Sharingan Damage +60%, After Each Action HP and Chakra +10%", "Itachi Uchiha"],
    [98, "Jet-Black Suit", "Resistance", "Incoming Sharingan Damage reduced, Sharingan Damage +10%", "Incoming Sharingan Damage Halved, Sharingan Damage +20%, Immune to Seal", "All Itachi Uchiha Units (Except Itachi Uchiha ANBU)"],
    [99, "Moon-White Suit", "Resistance", "Incoming Secret Skill Damage reduced. Secret Damage +10%", "Incoming Secret Skill Damage Halved, Secret Damage +20%, Immune to Paralysis", "All Deidara Units"],
    [100, "Blueish-Purple Suit", "Resistance", "Incoming Weapon Damage reduced, Weapon Damage +10%", "Incoming Weapon Damage Halved, Weapon skill Damage +20%, Immune to Poison", "All Sasori Units"],
    [101, "Zero", "Chakra", "Gain 10% Chakra After Each Action, Rinnegan Jutsu Damage +10%", "Gain 10% Chakra and HP After Each Action, Rinnegan Jutsu Damage +50%", "All Pain Units"],
    [102, "Makeout Tactics", "Skill", "Lightning Style & Sharingan Damage +20%, Max HP +20%", "Lightning Style & Sharingan Damage +50%, Max HP +40%", "All Kakashi Hatake Units"],
    [102, "Sage Scroll", "Skill", "Max HP +30%, Sage Jutsu Damage +40%", "Max HP and ATK +40%, Sage Jutsu Damage +100%", "All Naruto Uzumaki Units"],
    [103, "Temari's Fan", "Skill", "Wind type damage +30%, SPD +10%", "Skill type damage +70%, SPD +20%, Incoming Lightning type damage halved", "All Temari Units"],
    [104, "Mizukage's Hat", "Skill", "Water and Fire Style Damage +20%. Chance to be immune to debuffs", "Lava and Boil Style Jutsu Damage +70%, Immune to debuffs", "All Mei Terumi Units"],
    [105, "Sasuke's Waist Clasp", "Resistance", "Incoming Sharingan damage halved", "Immune to Sharingan damage. After each action, HP and Chakra recovered 10%", "Sasuke Uchiha"],
    [106, "Sasuke's Chidori-Sword", "Stats", "ATK and Sharingan damage +30%", "ATK and Sharingan damage +100%", "Sasuke Uchiha"],
    [107, "Sakura's Gloves", "Stats", "ATK and Taijutsu type skill Damage +30%", "ATK and Taijutsu type skill Damage +80%", "All Sakura Haruno Units"],
    [108, "Poison Disabling Medicine", "Resistance", "Poison/Toxic effect duration halved", "Immune to Poison/Toxic. Chakra cost -10%. Medical ninjutsu HP recovery +60%.", "All Sakura Haruno Units"],
    [109, "White Fang", "Stats", "ATK +40%, SPD +20%", "ATK +80%, SPD +40%", "All Young Kakashi Hatake Units"],
    [110, "Obito's Goggles", "Additional Effect", "Reduced damage from Sharingan Jutsu & HP +10%", "Receive half damage from Sharingan Jutsu, HP & DEF +40%", "All Young Obito Uchiha Units"],
    [111, "Medical Pack", "Skill", "Effect of Recovery skills increased by 20%", "Effect of Recovery Skills +60%, HP and DEF increased by 5000", "All Rin Nohara Units"],
    [112, "Medical Pack", "Skill", "Effect of Recovery skills increased by 20%", "Effect of Recovery Skills +60%, HP and DEF increased by 5000", "All Rin Nohara Units"],
    [113, "Team Minato's Backpack", "Resistance", "Reduced Damage from Fire, Wind and Lightning Stlye Jutsu, SPD -30%", "Half Damage from Fire, Wind and Lightning Stlye Jutsu", "Team Minato: Young Kakashi & Obito, Rin Nohara, and Jonin Minato"],
    [114, "Mazo Stakes", "Stats", "ATK and DEF +40%", "ATK and DEF +70%, Chakra Cost Reduced by 15%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
    [115, "Battle Mask", "Skill", "Fire Style and Sharingan Damage +20%", "HP +40%, Jutsu Damage +70%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
    [116, "Heaven Scroll", "Additional Effect", "When damaged, chance to recover chakra +5%", "When damaged chance to recover chakra 100%, HP +50%, and Skill Damage +30%", "Pre-Shippuden Team 7: (Naruto, Sasuke, & Sakura) and all Anko Mitarashi units"],
    [117, "Earth Scroll", "Additional Effect", "When damaged, chance to recover HP +5%", "When damaged chance to recover HP 100%, Chakra +50%, and Skill Damage +30%", "All Zaku, Dosu, & Kin Units, Adult Orochimaru (Except Sannin-era)"],
    [118, "Sasuke's Shuriken", "Stats", "ATK +60%, SPD +10%", "ATK +100%, SPD +30%, Fire type damage +50%", "Pre-Shippuden Sasuke Uchiha Units"],
    [119, "Sage Horn", "Skill", "Sage Type Jutsu and HP +10%", "Sage Type Jutsu and HP +70%", "Sage Mode Kabuto Yakushi Units"],
    [120, "Kabuto's Glasses", "Resistance", "Genjutsu/Confusion status halved", "Immune to negative effects, Attack and Defense +70%", "All Kabuto Yakushi Units"],
    [121, "Sasuke's Bow", "Skill", "Lightning Style Jutsu Damage and ATK +10%", "Lightning Style Jutsu Damage and ATK +60%", "All Sasuke Uchiha Units"],
    [122, "Itachi's Crow", "Additional Effect", "Regenerate 10% Chakra after an Action, Sharingan Damage +10%", "Regenerate 10% Chakra and HP after an Action, Sharingan Damage +60%", "All Itachi Uchiha Units"],
    [123, "Waist Clasp of the Sound Five", "Resistance", "Chance of falling under the sealed status is halved", "Immunity to Sealed and Confusion statuses. HP and DEF increased by 70%", "Sound Five (Jirobo, Tayuya, Sakon/Ukon, and Kidomaru, & Kimimaro Kaguya) Units"],
    [124, "Tayuya's Flute", "Skill", "ATK and SPD +20%, Genjutsu Skill Damage +20%", "ATK and SPD +50%, Genjutsu Skill Damage +100%", "All Tayuya Units"],
    [125, "Kamatari's Lantern", "Additional Effect", "Regenerate 5% Chakra after an Action, Wind Style Jutsu Damage +10%", "Regenerate 15% Chakra after an Action, All Jutsu's Damage +30%", "All Temari Units"],
    [125, "Kunai and Paper Bomb", "Stats", "HP and ATK +40%", "HP and ATK +80%, Secret Type Jutsu Damage +60%", "All Shikamaru Nara Units"],
    [126, "Madara's Fan", "Skill", "Fire Style and Rinnegan Jutsu Damage +20%", "All Jutsu Damage and ATK +60%", "All Madara Uchiha Units"],
    [127, "Hashirama's Cells", "Additional Effect", "Chance to grant immunity to skills, but -15% HP per turn", "+50% HP, greater chance of granting immunity to skills", "All Madara Uchiha Units"],
    [128, "Junk Food", "Additional Effect", "Max HP +15%", "None", "None"],
    [129, "Gamakichi Netsuke", "Additional Effect", "Reduced Damage from Fire, Sharingan and Lightning Style Jutsu", "Half Damage from Fire, Sharingan and Lightning Style Jutsu, Summoning jutsu damage+100%", "All Naruto Uzumaki Units"],
    [130, "Aoda Netsuke", "Additional Effect", "Reduced Damage from Taijutsu, SPD +20%", "Taijutsu Damage halved, SPD +40%, Summoning jutsu damage +80%", "All Sasuke Uchiha Units"],
    [131, "Katsuyu Netsuke", "Additional Effect", "Reduced Damage from Wind and Sage Jutsu", "Reduced damage from all skills. Immune to debuffs.", "All Sakura Haruno Units"],
    [132, "Pakkun Netsuke", "Additional Effect", "After Each Turn Recover 5% HP & Chakra", "After Each Turn Recover 10% HP and Chakra, Skill Damage +50%", "All Kakashi Hatake Units"],
    [133, "Inoshikacho Piercing (Ino)", "Stats", "HP and SPD +20%", "HP & SPD +50%, Recovery skills increase recovery +50%", "Shippuden-era Ino Yamanaka Units"],
    [134, "Inoshikacho Piercing (Shika)", "Stats", "HP and DEF +20%", "HP & DEF + 50%, Weaknesses are disabled", "Shippuden-era Shikamaru Nara Units"],
    [135, "Inoshikacho Piercing (Cho)", "Stats", "HP and ATK +20%", "HP, ATK, and Secret type skill damage +50%", "Shippuden-era Choji Akimichi Units"],
    [136, "Bingo Book", "Skill", "Wind Style Skill Damage +20%", "HP & ATK +30%, All Skill type damage +80%", "All Kakuzu Units"],
    [137, "Kakuzu's Ryo", "Additional Effect", "Money gained from missions +20%", "Money gained from missions +20%, ATK & DEF +50%", "All Kakuzu Units"],
    [138, "Summoning Scroll", "Skill", "Summoning type skill damage +20%, HP & ATK + 20%", "Summoning type skill damage +60%, HP & ATK + 40%", "Pre-Shippuden Kakashi Hatake Units"],
    [139, "Executioner's Blade", "Stats", "HP & ATK +20%, Unique skill type damage +30%", "HP, ATK, & All Skill type damage +50%", "All Zabuza Momochi Units"],
    [140, "Senbon", "Stats", "ATK & SPD +20%. Water Type skill damage +30%", "ATK, SPD, and All skill type damage +50%", "All Haku Units"],
    [141, "Hokage Necklace", "Chakra", "Chakra consumption reduced by 10%. Recovery skills have a bonus 10% recovery", "Chakra Consumption reduced by 25%. All damaging and recovery skills have a 60% boost.", "All Adult Tsunade and Hashirama Senju Units"],
    [142, "Sannin: Jiraiya's Forehead Protector", "Chakra", "Chakra consumption reduced by 5%. Genjutsu and Summoning Skill Damage increased by 20%", "Chakra Consumption reduced by 20%. All Skill damage increased by 80%.", "All Adult Jiraiya Units"],
    [143, "Deidara's Scope", "Skill", "Secret Type Jutsu Damage +20%, SPD +20%", "Secret Type Jutsu Damage +50%, SPD +50%", "All Deidara Units"],
    [144, "Gaara's Sand Gourd", "Stats", "DEF +20%, Unique Type Damage +20%", "ATK & DEF +50%, Unique type Damage +50%", "All Shippuden Gaara Units"],
    [145, "Hashirama's Armor", "Stats", "Maximum HP & DEF +30%", "Maximum HP & DEF +50%. HP recovered by 15% after each action.", "All Hashirama Senju Units"],
    [146, "Tobirama's Forehead Protector", "Chakra", "Chakra consumption decreased by 7%. Slight chance to dodge skills.", "Chakra consumption decreased by 20%. Chance to dodge skills.", "All Tobirama Senju Units"],
    [147, "Hiruzen's Shuriken", "Stats", "ATK +80%", "ATK +120%. Skill Damage +30%", "All Hiruzen Senju Units"],
    [148, "Obito's Truth-Seeking Ball", "Additional Effect", "All Skill type damage +40%, Chakra recovery amount halved", "All skill type damage +70%, great chance of skill avoidance", "All Ten-Tails Obito Uchiha Units"],
    [149, "Obito's Staff", "Stats", "ATK & SPD +50%, HP reduced by 30% after every action", "ATK & DEF + 80%, SPD +40%", "All Ten-Tails Obito Uchiha Units"],
    [150, "Anniversary Forehead Protector", "Chakra", "Chakra Consumption reduced by 5%", "Chakra consumption reduced by 15%. ATK and SPD +30%", "All Sakura Haruno Units"],
    [151, "Anniversary Ladle", "Skill", "Unique type skill damage +10%. Weakness damage received is reduced", "All Skill types +30% damage. Weakness damage received is halved", "All Kushina Uzumaki Units"],
    [152, "Anniversary Pouch", "Stats", "HP +20%", "HP +30%, Skill damage received is reduced", "All Hinata Hyuga Units"],
    [153, "Anniversary Fan", "Stats", "SPD +30%", "ATK, DEF & SPD +30%", "All Temari Units"],
    [154, "General Election Testimony", "Additional Effect", "Chakra recovery +5%", "Chakra recovery +40%, Unique skill type damage +20%", "Sakura, Kushina, Hinata, Temari"],
    [155, "Vermillion", "Chakra", "Chakra restore +10% after each action, Sharingan Type Skill damage +10%", "Chakra restore +20% after each action, All skill type damage + 50%", "All Itachi Uchiha Units (Except Itachi Uchiha ANBU)"],
    [156, "Itachi's ANBU Mask", "Stats", "SPD +20%, Weapon type skill damage +30%", "ATK & SPD +50%, all skill type damage +100%", "Itachi Uchiha"],
    [157, "Throne", "Resistance", "Genjutsu damage received is halved, but HP is reduced 15% after each action", "Damage from Fire style, Sharingan and Genjutsu skill is halved, All skill type damage +30%.", "All Itachi Uchiha Units"],
    [158, "Ay's Belt", "Skill", "Taijutsu Skill damage, ATK, & SPD +20%", "Taijutsu skill damage +70%, ATK & SPD + 30%", "All Ay (Fourth Raikage) Units"],
    [159, "Bee's Pencil", "Skill", "Lightning type skill damage & ATK + 30%", "All skill type damage +70%. ATK +50%", "All Killer Bee Units"],
    [160, "Samehada", "Skill", "Water style type skill damage + 30%. HP +10%", "Water style type skill damage +70%. HP & ATK +30%", "All Kisame Hoshigaki Units"],
    [161, "South", "Chakra", "Gain 10% Chakra after each action & Water style Jutsu Damage +10%.", "Gain 10% Chakra and HP after each action. Water style Jutsu Damage +60%", "All Kisame Hoshigaki Units"],
    [162, "Sage Mode Coat", "Resistance", "Reduce duration of negative status & after each action -15% HP", "Halve duration of negative status & low chance to dodge skills", "Sage Mode Naruto Units"],
    [163, "Konohamaru's Scarf", "Stats", "ATK +70% & SPD +10%", "ATK +100%, SPD +20%, & all skill type damage +50%", "All Konohamaru Sarutobi Units"],
    [164, "Sun Necklace", "Stats", "ATK +100% & after each action HP -15%", "ATK & Skill Damage +100%, Jutsu casting speed increased by 1 step", "All Pain Units"],
    [165, "White Bouquet", "Additional Effect", "Recover Chakra by 5% after every action", "Byakugan skill damage +30%, recover Chakra by 20% after every action", "All Hinata Hyuga Units"],
    [166, "Yellow Bouquet", "Additional Effect", "Recover HP and Chakra by 3% after every action", "All Skill Damage +30%, recover 10% HP and Chakra after every action", "All Mei Terumi Units"],
    [167, "Red Bouquet", "Additional Effect", "Recover 5% HP after every action", "All Skill Damage +30%, recover 20% HP after every action", "All Kushina Uzumaki Units"],
    [168, "Classy Sake Cups", "Additional Effect", "Reduce the chance of falling into a negative state", "HP and QCK +50%, immune to negative status", "All Kurenai Yuhi Units"],
    [169, "Gai's Nunchucks", "Stats", "ATK +80%, SPD +10%, but HP -30%", "ATK +100%, SPD +30%, HP +5000", "All Might Gai Units"],
    [170, "Precious Stone", "Skill", "Max HP and Particle Style Skill damage +30%", "HP +70%, all skill type damage +120%", "All Oonoki (Third Tsuchikage) Units"],
    [171, "Mu's Bandages", "Skill", "Particle Style skill damage +20%, Max HP and DEF +30%", "All skill type damage +120%, HP & DEF +80%", "All Mu (Second Tsuchikage) Units"],
    [172, "Mu's Bandana", "Chakra", "Chakra consumption reduced by 5%, ATK +20%", "Chakra consumption reduced by 10%, ATK & All Skill type Damage +50%", "All Mu (Second Tsuchikage) Units"],
    [173, "Iwagakure Forehead Protector", "Chakra", "Chakra consumption reduced by 7%, recovery from healing skills +30%", "None", "None"],
    [174, "Iwagakure Sandals", "Stats", "SPD +30%, recovery from healing skills +20%", "None", "None"],
    [174, "Iwagakure Kunai", "Stats", "ATK +50%, DEF & HP +20%", "None", "None"],
    [175, "Jiraiya's Notepad", "Skill", "Fire Style and Summoning skill type damage +20%", "All skill type damage +70%, Max HP & SPD +30%", "All Adult Jiraiya Units"],
    [176, "Bee's White Scarf", "Stats", "ATK +70%, HP +10%", "ATK +100%, HP +20%. All skill types damage +50%", "All Killer Bee Units"],
    [175, "Iruka's Letter", "Additional Effect", "ATK, DEF & SPD +10%", "ATK, DEF & SPD +30%. Skill casting speed is up by 1 stage", "Kurama Link Mode Naruto Uzumaki units"],
    [176, "Ay's Haori Jacket", "Resistance", "Incoming Lightning Style and Taijutsu type skill damage is reduced, chakra consumption reduced by 5%", "Incoming Lightning Style and Taijutsu type skill damage is halved, chakra consumption reduced by 15%", "All Ay (Fourth Raikage) Units"],
    [177, "Ay's Right Arm Weight", "Stats", "ATK +70% & SPD +10%", "ATK +120% & SPD +20%. All skill types damage +30%", "All Ay (Fourth Raikage) Units"],
    [177, "Kushina's Ladle", "Skill", "Unique type skill damage and ATK +20%", "All Skill types damage & ATK +50%", "All Kushina Uzumaki Units"],
    [178, "Flaky Jersey", "Resistance", "Reduced damage from Wind Style Jutsu", "Half damage from Wind and Unique Style Jutsu, Chance to dodge Skills", "All pre-Shippuden Naruto Uzamaki Units and All Boruto Uzumaki Units"],
    [179, "Sarada's Glasses", "Resistance", "Chance of falling under the sealed status is halved", "Immunity to negative status, skill damage +40%", "All Sarada Uchiha Units"],
    [180, "Seventh Hokage's Cloak", "Stats", "HP & DEF +30%", "HP & DEF +80%, SPD +40%", "Adult Naruto Uzumaki Units"],
    [181, "Sasuke's Cloak", "Stats", "HP & SPD +30%", "HP, SPD & Skill damage +40%", "Adult Sasuke Uchiha Units"],
    [182, "Jugo's Cells", "Stats", "ATK & SPD +40%. HP reduced by 40% after every action", "Immune to paralysis, ATK & SPD +50%", "Shippuden-era Sasuke Uchiha"],
    [183, "Suigetsu's Water Bottle", "Additional Effect", "HP restores by 10% after every action", "HP and Chakra restore by 20% after every action, skill damage +50%", "All Suigetsu Units"],
    [184, "Photo of Sasuke", "Additional Effect", "DEF +20%, recover Chakra by 6% after every action", "DEF and recovery skill effect +50%, recover Chakra by 20% after every action", "All Karin Units"],
    [185, "Bird", "Additional Effect", "Rare chance to dodge skills", "Medium chance to dodge skills, recover HP and Chakra by 20% after every action", "All Jugo Units"],
    [186, "Sasuke's White Jacket", "Stats", "Max HP & SPD +20%", "Max HP & ATK +100%, recover Chakra by 10% after every action", "All Karin and Shippuden-era Sasuke Uchiha Units"],
    [187, "Hebi's Cloak", "Resistance", "Incoming Fire, Water, Wind, Earth, and Lightning Style type skill damage is reduced", "Incoming all skill type damage is reduced, max HP & DEF +30%", "All Hebi Members"],
    [188, "Suigetsu's Head Cleaver", "Stats", "ATK and Weapon type skill damage +40%", "ATK and all skill type damage +80%, chance to dodge skills", "All Suigetsu Units"],
    [189, "Curtain", "Stats", "ATK +70% & Max HP +10%", "ATK +100%, Max HP +20%, all skill type damage +50%", "All Jugo Units"],
    [190, "Clay", "Additional Effect", "ATK and Secret type skill damage +30%", "ATK and skill damage +60%, skill casting speed is up by 1 stage", "All Deidara Units"],
    [191, "Sasuke's Cursed Seal", "Stats", "Low chance to dodge skills, lose HP by 5% after every action", "High chance to dodge skills, max Chakra +100", "Sasuke Uchiha"],
    [192, "Orochimaru's Sword of Kusanagi", "Stats", "ATK +90%", "ATK +120%, all skill type damage +70%", "All Adult Orochimaru Units (Except Sannin-era)"],
    [193, "Popsicle", "Stats", "ATK & DEF +15%", "None", "None"],
    [194, "Madara's Staff", "Stats", "ATK and Max HP +50%, lose Chakra by 20% after every action", "ATK and max HP +80%, SPD +40%", "Six Paths Madara Uchiha"],
    [195, "Dad's Kunai", "Stats", "ATK +60% & SPD +20%", "ATK +120%, SPD & all skill type damage +30%", "Six Paths Naruto Uzumaki, All Minato Namikaze Units"],
    [196, "Sword of Nunoboko", "Stats", "ATK +200%, reduction in max HP by 50%", "ATK +150%, max HP +50%", "All Ten-Tails Obito Uchiha Units"],
    [197, "Obito's Memories", "Chakra", "Reduction in Chakra consumption by 20%, lose Chakra by 20% after every action", "Reduction in Chakra consumption by 30%, recover Chakra by 20% after every action", "All Ten-Tails Obito Uchiha Units"],
    [198, "Obito's Imaginary Hat", "Skill", "All skill type damage +40%, SPD -40%", "All skill type damage +60%, DEF & SPD +40%", "All Ten-Tails Obito Uchiha Units"],
    [199, "Transplanted Cells", "Chakra", "Recover chakra by 20% after every action, lose HP by 20% after every action", "Recover chakra by 20% after every action, reduction in Chakra consumption by 20%", "Sage Mode Kabuto Yakushi Units, Sasuke Uchiha"],
    [200, "Gamble", "Stats", "Max HP & ATK +40%", "Max HP & ATK +80%, all skill type damage +20%", "All Adult Tsunade Units"],
    [201, "Tsunade's Katsuyu Netsuke", "Additional Effect", "Recovery skill effect +20%", "Recovery skill effect +70%, incoming skill damage is reduced", "All Adult Tsunade Units"],
    [202, "Straw Hat", "Chakra", "Reduction in Chakra consumption by 15%", "Reduction in Chakra consumption by 25%, max HP +50%", "All Haruno Sakura Units"],
    [203, "Pink Jacket", "Resistance", "When HP is over 80%, chance of being inflicted with status effects is halved", "Immunity to status effects, max HP and defense +50%", "All Hyuga Hinata Units"],
    [204, "Yellow Flower Hairpin", "Chakra", "Recover Chakra by 10% after every action", "Recover Chakra by 20% after every action, chance of HP recovery by 10% when attacked", "All Yamanaka Ino Units"],
    [205, "Lifebuoy", "Stats", "ATK & DEF +30%", "ATK and DEF +80%, skill damage +20%", "All Tenten Units"],
    [206, "Whistle", "Additional Effect", "Max HP & ATK +30%", "Max HP & ATK +50%, skill damage +30%", "All Umino Iruka Units"],
    [207, "Surfboard", "Stats", "ATK and SPD +30%", "ATK & SPD +50%, Lightning Style type skill damage +20%", "Adult Kakashi Hatake Units"],
    [208, "Beach Umbrella", "Skill", "Wind Style type skill damage +40%", "All skill type damage +70%, ATK & DEF +40%", "All Temari Units"],
    [209, "Tsunade's Sun Oil", "Resistance", "DEF +30%, immunity to Water Style type skill damage for up to 3 actions", "DEF +50%, immunity to Water Style type skill damage. Medium chance to dodge skills", "All Adult Tsunade Units"],
    [210, "Naruto's Palm Seal", "Additional Effect", "Max Chakra increased by 5", "Full HP and Chakra recovery when HP reaches 0 (1 time only)", "Six Paths Naruto Uzumaki"],
    [211, "Naruto's Six Paths Coat", "Resistance", "Reduction in incoming damage from all skill types (except Six Paths), reduction in HP by 20% during every action", "Reduction in incoming damage from all skill types (except Six Paths), immunity to status effects", "Six Paths Naruto Uzumaki"],
    [212, "Naruto's Truth-Seeking Ball", "Skill", "All skill type damage +40%, reduction in max HP by 50%", "Max HP and all skill type damage +100%", "Six Paths Naruto Uzumaki"],
    [213, "Sasuke's Palm Seal", "Additional Effect", "Max Chakra increased by 5", "Full HP and Chakra recovery when HP reaches 0 (1 time only)", "Six Paths Sasuke Uchiha"],
    [214, "Cursed Seal Sage Power", "Skill", "Sharingan and Rinnegan type skill damage +30%", "All skill type damage +100%, SPD +50%", "Six Paths Sasuke Uchiha"],
    [215, "Madara's Truth-Seeking Ball", "Skill", "Rinnegan skill type damage +40%, SPD -30%", "All skill type damage +80%, skill cast speed increased by 1 stage", "Six Paths Madara Uchiha"],
    [216, "Madara's Six Paths Coat", "Resistance", "Chance of received status effects and debuffs halved, reduction in DEF by 50%", "Immunity to status effects and debuffs, max HP & DEF +50%", "Six Paths Madara Uchiha"],
    [217, "Tailed Beast Chakra", "Chakra", "For the first 9 actions, Chakra consumption is reduced by 15%", "For the first 9 actions, Chakra consumption is halved and skill damage +50%", "Six Paths Naruto Uzumaki"],
    [218, "Hanzo's Defence Mask", "Chakra", "Recover 5% of Chakra at the end of every action. Fire Skill Damage +10%", "Recover 20% of Chakra at the end of every action. All Skill Damage +30%", "All Hanzo Units"],
    [219, "Hanzo's Explosive Tags", "Skill", "Fire Skill Damage & ATK +20%", "Fire Skill Damage & ATK +70%. Skill Crit Chance +40%", "All Hanzo Units"],
    [220, "Jiraiya's War Vest", "Additional Effect", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Jiraiya"],
    [221, "Tsunade's War Vest", "Additional Effect", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Tsunade"],
    [222, "Orochimaru's War Vest", "Additional Effect", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Orochimaru"],
    [223, "Jiraiya's Frog Suit", "Resistance", "Incoming Fire and Water Skill Damage are reduced. DEF -20%", "Incoming Skill Damage Reduced. ATK & DEF +40%", "All Jiraiya Units"],
    [224, "Tsunade's Pouch", "Skill", "Healing Skills +20%. Maximum HP +20%", "Healing Skills +50%. Maximum HP & DEF +30%", "All Tsunade Units"],
    [225, "Orochimaru's Mantle", "Resistance", "Reduced chance of being affected by abnormal states", "Abnormal State effects are halved. Maximum HP & SPD +30%", "All Orochimaru Units"],
    [226, "Personal Tracksuit", "Resistance", "Incoming Taijutsu and Weapon type skill damage is reduced, max HP +20%", "Incoming Taijutsu and Weapon type skill damage is halved, chance to dodge skills, max HP +40%", "All Might Gai and Rock Lee Units"],
    [227, "Lee's Weights", "Stats", "Max HP & ATK +60%, DEF -30%", "Max HP & ATK +100%, Skill Damage +30%", "All Rock Lee Units"],
    [228, "Lee's Bandages", "Skill", "Taijutsu Skill Type damage +30%, SPD +20%", "Max HP & ATK +100%, Skill Damage +30%", "All Rock Lee Units"],
    [229, "Kamatari's Scythe", "Stats", "ATK & SPD +30%", "HP & ATK +70%, SPD +40%", "All Temari Units"],
    [230, "Sunagakure Socks", "Additional Effect", "SPD +50. Restores 2% HP when hit", "SPD +80. Restores 10% HP when hit", "Shippuden era Temari, Gaara, and Kankuro Units"],
    [231, "Giant Shuriken", "Stats", "ATK +100%, SPD +20%", "None", "None"],
    [231, "Amegakure Forehead Protector", "Chakra", "Chakra consumption is reduced by 10%, recover 10% of Chakra after every action", "None", "None"],
    [232, "Bamboo Pipe", "Skill", "All type skill damage +30%, Water Style type skill damage additional +50%", "None", "None"],
    [233, "Eight Trigrams Seal", "Additional Effect", "Resistance to seal status", "Half resistance to debuffs and status effects, recover 10% of HP and Chakra after every action", "Pre-Shippuden Naruto Uzumaki Units"],
    [234, "Leaked Nine-Tails' Chakra", "Chakra", "Max Chakra +10, reduction in HP by 5% after every action", "Max Chakra +50, all type skill damage +50%", "Pre-Shippuden Naruto Uzumaki Units"],
    [235, "Sasuke's Cursed Seal", "Additional Effect", "Recover 7% of Chakra and lose 5% of HP after every action", "Recover 10% of Chakra after every action, Max Chakra +50", "Pre-Shippuden Sasuke Uchiha Units"],
    [235, "Sasuke's Forehead Protector", "Chakra", "Chakra consumption is reduced by 5%, ATK +20%", "Chakra consumption is reduced by 15%. Max HP, ATK & DEF +20%", "Pre-Shippuden Sasuke Uchiha Units"],
    [236, "Third Kazekage (Puppet)", "Skill", "Weapon and Magnet Style type skill damage +40%, but HP is reduced by 10% after each turn", "All types skill damage +70%. Skill cast speed increased by 1 step", "All Sasori Units"],
    [237, "Jewel", "Chakra", "Chakra restore by 10% after each turn, Weapon type skill damage +10%", "Chakra restore by 20% after each turn, all types skill damage +50%", "All Sasori Units"],
    [237, "Naruto's Jersey", "Stats", "ATK and Wind Style type skill damage +30%", "ATK and Wind Style type skill damage +100%", "Shippuden-era Naruto Uzumaki Units"],
    [238, "Naruto's Forehead Protector", "Chakra", "Chakra consumption reduced by 5%, SPD +20%", "Chakra consumption reduced by 10%. Max HP, ATK & SPD +20%", "Shippuden-era Naruto Uzumaki Units"],
    [239, "Sasuke's Loincloth", "Resistance", "Reduced incoming damage from Wind Style type skills", "Halved incoming damage from Wind Style and Unique type skills. Skill damage +30%", "Shippuden-era Sasuke Uchiha Units"],
    [240, "Sasuke's White Snake", "Additional Effect", "Recover 10% of HP after every action. Lightning Style type skill damage +10%", "Recover 10% of HP and Chakra after every action. Lightning Style type skill damage +60%", "Shippuden-era Sasuke Uchiha Units"],
    [241, "Kakashi's Forehead Protector", "Chakra", "Chakra consumption reduced by 10%", "Chakra consumption reduced by 15%, recover 10% of HP every action", "All Adult Kakashi Hatake Units"],
    [242, "Kakashi's Undershirt", "Resistance", "Very low chance of skill immunity, max HP reduced by 50%", "Max HP +40%, medium chance of skill immunity", "All Adult Kakashi Hatake Units"],
    [243, "Makeout Violence", "Stats", "ATK +90%", "ATK +130%, all type skill damage +30%", "All Adult Kakashi Hatake Units"],
    [244, "Naruto's Giant Scroll", "Skill", "ATK and Sage Art type skill damage +40%", "For the first 3 actions, ATK and Sage Art type skill damage +80%. For 3 turns after, ATK and Sage Art type skill damage +150%", "Sage Mode Naruto Uzumaki Units"],
    [245, "Fukusaku Netsuke", "Additional Effect", "Reduced incoming damage from Sharingan and Rinnegan type skills", "Halved incoming damage from Sharingan and Rinnegan type skills. Sage type skill damage +60%", "Sage Mode Naruto Uzumaki Units"],
    [246, "Sage Art Chakra", "Chakra", "Recover 5% of Chakra after every action", "Recover 10% of Chakra after every action, max HP and Sage Art type skill damage +50%", "Sage Mode Naruto Uzumaki Units, All adult Jiraiya Units (except Sannin)"],
    [247, "Sword of Kusanagi - Chidori Blade", "Stats", "ATK +100%", "ATK +150%, skill cast speed increased by 1 step", "Shippuden-era Sasuke Uchiha Units"],
    [248, "Sasuke's Wristbands", "Resistance", "Reduced incoming damage from Wind Style and Sage Style type skills, SPD +10%", "Halved incoming damage from Wind Style and Sage Style type skills. ATK, DEF & SPD +50%", "Shippuden-era Sasuke Uchiha Units"],
    [249, "Sasuke's Hawk", "Additional Effect", "Recover 10% of Chakra after every action, Sharingan type skill damage +10%", "Recover 10% of HP and Chakra after every action. Sharingan type skill damage +60%", "Shippuden-era Sasuke Uchiha Units"],
    [250, "Frog Gift", "Additional Effect", "Max HP +30%, chance to recover 5% of HP when attacked", "Max HP +50%, recover 15% of HP when attacked", "All Adult Nagato, Konan, and Yahiko Units"],
    [251, "Nagato's Kunai", "Stats", "ATK +70%, DEF +30%", "ATK +100%. DEF and skill damage +40%", "All Adult Nagato Units"],
    [252, "Old Akatsuki Cloak", "Resistance", "Reduced incoming damage from Sharingan, Byakugan, and Rinnegan type skills", "Reduced incoming damage from all skill types except Wind Style, Sage Style, and Six Paths", "All Adult Nagato, Konan, and Yahiko Units"],
    [253, "Ino's Hairclips", "Skill", "Recovery skill effect +20%", "Recovery skill effect +50%, skill cast speed increased by 1 step", "Shippuden-era Ino Yamanaka Units"],
    [254, "Chouji's Chest Protecto", "Skill", "Secret type skill damage +50%, SPD -20%", "All type skill damage and DEF +70%, halved resistance to debuffs", "Shippuden-era Choji Akimichi Units"],
    [255, "Asuma's Chakra Blade", "Skill", "Secret and Weapon type skill damage +30%", "All type skill damage +70%, SPD +40%", "Shippuden-era Shikamaru Nara and Asuma Sarutobi Units"],
    [256, "Kabuto's Hood", "Additional Effect", "All skill type damage +10%", "All skill type damage +30%, recover 10% of Chakra after every action", "Sage Mode Kabuto Units"],
    [257, "Kabuto's Special Blood Transfusion Pack", "Stats", "Max HP and ATK +50%", "Max HP, ATK, DEF & SPD +80%", "Sage Mode Kabuto Units"],
    [258, "Itachi's Cloak", "Resistance", "Incoming Sharingan damage halved", "Incoming Sharingan damage halved, DEF +100%", "Edo Tensei Itachi Uchiha Units"],
    [258, "Nagato's Cloak", "Resistance", "Incoming Rinnegan damage halved", "Incoming Rinnegan damage halved, DEF +100%", "Edo Tensei Nagato Units"],
    [259, "Shisui's Eye", "Additional Effect", "Very low chance to dodge skills", "Chance to dodge skills, immunity to status effects", "All Itachi Uchiha and Shisui Uchiha Units"],
    [260, "Asura Path Arm", "Skill", "Rinnegan type skill damage +40%", "Rinnegan type skill damage and ATK +80%", "Edo Tensei Nagato Units"],
    [261, "Obito's Chain", "Additional Effect", "All type skill damage +10%", "All type skill damage +30%, critical rate +30% for skills with critical conditions", "Adult Obito Uchiha Units (except Ten-Tails)"],
    [262, "Utakata's Bubble Blower", "Stats", "ATK +70%, SPD +10%", "ATK +100%, SPD +20%, all type skill damage +50%", "Utakata Units"],
    [263, "Nagato's Tube", "Skill", "Wind Style skill damage +30%, max HP +10%", "All type skill damage +80%, max HP +40%", "Adult Nagato Units (except Edo)"],
    [264, "Yahiko's Sword", "Stats", "ATK 100%", "ATK 150%, all type skill damage +20%, critical rate +20% for skills with critical conditions", "Adult Yahiko Units"],
    [265, "Flaky Jersey", "Stats", "Max HP & DEF +50%", "Max HP & DEF +90%, skill cast speed increased by 1 step", "All Shippuden-era Naruto Uzumaki Units"],
    [266, "Flaky Chainmail", "Resistance", "Low chance to dodge skills", "Low chance to dodge skills. When HP is over 50%, evasion rate is increased", "All Shippuden-era Naruto Uzumaki Units"],
    [267, "Sasuke's Acquisition Seal", "Skill", "Weapon and Lightning Style type skill damage +30%, SPD +10%", "Weapon and Lightning Style type skill damage +120%, SPD +40%", "All Shippuden-era Sasuke Uchiha Units"],
    [268, "Flaky Jacket", "Resistance", "Resistance to debuffs and status effects", "Halved resistance to debuffs and status effects. When HP is over 40%, halved incoming damage for all skill types", "All Shippuden-era Sasuke Uchiha Units"],
    [269, "Valley of the End Statue (Left)", "Additional Effect", "Recover 5% of Chakra and 3% of HP when attacked", "Recover 10% of Chakra and 5% of HP when attacked", "All Madara Uchiha and Sasuke Uchiha Units"],
    [269, "Valley of the End Statue (Right)", "Additional Effect", "Recover 5% of Chakra and 3% of HP when attacked", "Recover 10% of Chakra and 5% of HP when attacked", "All Hashirama Senju and Naruto Uzumaki Units"],
    [270, "Shortcake", "Additional Effect", "For the first 5 actions restore 20% HP", "None", "None"],
    [271, "Naruto's Shared Cake", "Additional Effect", "For the first 5 actions restore 99% HP", "None", "None"],
    [272, "Fourth Hokage Cloak", "Resistance", "Quickness +20%, very low chance of skill dodge.", "Max HP, SPD & skill damage +50%. Medium chance of skill dodge.", "All Hokage Minato Namikaze Units and Naruto Uzumaki (Chasing Your Dream)."],
    [273, "Shima's Home Cooking", "Additional Effect", "For the first 3 actions, immunity to all type skill damage. Max HP & SPD reduced by 30%.", "Critical rate & ATK +50%. For the first 3 actions, immunity to all type skill damage.", "All Sage Naruto Uzumaki and Jiraiya Units"],
    [274, "Ancestor Statue", "Skill", "All type skill damage +40%, but acquire weakness to all skills (excluding resistance and immunity)", "Max Chakra +20, Sage Art type skill damage +120%", "All Sage Naruto Uzumaki and Jiraiya Units"],
    [275, "Hashirama's Giant Scroll", "Skill", "Max HP & Sage Art type skill damage +30%", "Max HP & Sage Art type skill damage +80%", "All Hashirama Senju units"],
    [276, "Hashirama's New Armor", "Stats", "ATK & DEF +50%", "ATK & DEF +50%, chance of full HP recovery after every action", "All Hashirama Senju units"],
    [277, "Tobirama's Ninja Sword", "Additional Effect", "ATK +40%", "ATK +60%, all type skill damage +60%", "All Tobirama Senju Units"],
    [278, "Tobirama's Ninja Armor", "Stats", "ATK & SPD +50%", "ATK & SPD +50%, chance of SPD +100% after every action", "All Tobirama Senju Units"],
    [279, "Rasa's Gold Dust", "Stats", "Max HP +50%", "Max HP & ATK +100%, recover 15% of HP after every action", "All Rasa Units"],
    [280, "Fourth Kazekage Hat", "Skill", "Magnetic Style type skill damage +30%", "All type skill damage +80%, recover 10% of Chakra after every action", "All Rasa Units"],
    [281, "Gaara's Tattoo", "Additional Effect", "Resistance to status effects. Recover 5% of HP when attacked", "Halved resistance to status effects and debuffs. Recover 10% of HP when attacked", "All Gaara Units"],
    [282, "Fifth Kazekage Hat", "Skill", "Unique and Sealing type skill damage +40%", "All type skill damage +80%, max HP +60%", "All Shippuden-era Gaara Units"],
    [283, "Gengetsu's Gown", "Stats", "ATK & DEF +40%", "Max HP, ATK & DEF +100%", "All Gengetsu Hozuki Units"],
    [284, "Ohamaguri Netsuke", "Additional Effect", "Very low chance to dodge skills", "Dodge rate +50%, medium chance to dodge skills", "All Gengetsu Hozuki Units"],
    [285, "Second Mizukage Hat", "Skill", "Water Style type skill damage +30%", "All type skill damage +80%, recover 10% of HP after every action", "All Gengetsu Hozuki Units"],
    [286, "Temari's Vest", "Resistance", "Incoming Fire, Water, and Wind Style type skill damage reduced", "Incoming Fire, Water, and Wind Style type skill damage halved. Medium chance to dodge skills", "All Shippuden-era Temari Units"],
    [287, "Hiramekarei", "Skill", "Weapon type skill damage +30%, ATK +10%", "ATK and skill damage +70%, max Chakra +50", "All Choujuro Units"],
    [288, "Choujuro's Glasses", "Resistance", "Half resistance to Genjutsu and debuffs", "Immunity to Genjutsu and debuffs, max HP & ATK +50%", "All Choujuro Units"],
    [288, "Kimimaro's Hair Ornaments", "Chakra", "Recover 5% of Chakra after every action", "Recover 10% of Chakra after every action. Chakra cost reduced by 10%", "All Kimimaro Kaguya Units"],
    [289, "Kimimaro's Spine", "Stats", "ATK +150%, lose 30% of HP after every action", "ATK +150%, max HP +50%", "All Kimimaro Kaguya Units"],
    [290, "Hashirama's Giant Blade", "Additional Effect", "ATK +40%", "ATK +40%, additional 10 hits for skills with random damage", "All Hashirama Senju units"],
    [291, "Naruto's Racquet", "Skill", "Unique type skill damage +30%", "ATK & Unique type skill damage +60%. Immunity to seal status", "All Naruto Uzumaki Units"],
    [292, "Sasuke's Racquet", "Skill", "Fire Style type skill damage +30%", "ATK & Fire type skill damage +60%. Immunity to paralysis status", "All Sasuke Uchiha Units"],
    [293, "Sakura's Fan", "Skill", "Taijutsu and Unique type skill damage +30%", "Taijutsu and Unique type skil damage +80%. Recovery effect +50%", "All Sakura Haruno Units"],
    [294, "Hinata's Bath Set", "Skill", "Byakugan type skill damage +30%", "Byakugan type skill damage +80%, ATK & DEF +30%", "All Hinata Hyuga Units"],
    [295, "Jiraiya's Scroll", "Skill", "ATK & Sage Art type skill damage +20%", "Halved Chakra cost for the first 5 actions. After the 5th action and beyond, ATK & Sage Art type skill damage +150%", "All Jiraiya Units (excluding Sannin)"],
    [296, "Stone Sword of the Frog Elegy", "Stats", "ATK & SPD +40%", "Max HP, ATK & SPD +50%. Skill damage +30%", "All Jiraiya Units (excluding Sannin)"],
    [297, "Konan's Explosive Tag", "Stats", "Max HP & ATK +30%", "Max HP & ATK +100%. Skill damage +30%", "All Adult Konan Units"],
    [298, "Konan's Head Ornament", "Chakra", "Max Chakra +5", "Max Chakra +50. Recover 10% of HP after every action", "All Adult Konan Units"],
    [299, "Konan's Origami", "Skill", "Unique type skill damage +50%. Acquire weakness to Fire Style, Sharingan, and Sage Art type skills", "Skill damage +80%. Max HP & SPD +30%", "All Adult Konan Units"],
]












