window.chara=[
      {
          "cardId": "20000001",
          "modelId": "0",
          "charaType": "1",
          "cardSubName": "疾風の如く",
          "cardInformation": "木ノ葉一の問題児として名を馳せる忍者\r\nうずまきナルト。\r\n \r\n目立ちたがり屋で負けず嫌いな木ノ葉の\r\n下忍だ。",
          "bookNo": "3",
          "rare": "4",
          "motionType": "1",
          "attribute": "1",
          "abilityId1": "37",
          "abilityId2": "29",
          "battleSkillId1": "1",
          "battleSkillId2": "2",
          "leaderSkillId": "1",
          "runSkillId1": "0",
          "hp": "2384",
          "hpMax": "6676",
          "attack": "2454",
          "attackMax": "6872",
          "attackBehaveNum": "0",
          "defense": "2174",
          "defenseMax": "6087",
          "speed": "118",
          "speedMax": "118",
          "hitLot": "10000",
          "avoidanceLot": "1065",
          "criticalLot": "1320",
          "criticalDamageLot": "14550",
          "cost": "18",
          "price": "2400",
          "fusionExp": "1500",
          "fusionMaterialFlg": "0",
          "charaProfileId": "101",
          "defaultUnlockBit": "0",
          "fusionRuleId": null,
          "createTime": "2015-04-19 17:37:12",
          "createUserId": "1",
          "updateTime": "2015-04-19 17:37:12",
          "updateUserId": "1",
          "translated": "0"
        },
        {
          "cardId": "20000011",
          "modelId": "51",
          "charaType": "1",
          "cardSubName": "朱きチャクラ",
          "cardInformation": "目の前の強者との戦いは熾烈を極めた。”血継限界”という特異な資質を持つ白。ナルトとサスケは奮起するも、白の類稀なる術により、サスケがナルトをかばい倒されてしまう。万事休すと思われたその時、怒りが引き金となり、ナルトに変化が起きる。",
          "bookNo": "2",
          "rare": "3",
          "motionType": "1",
          "attribute": "3",
          "abilityId1": "40",
          "abilityId2": "38",
          "battleSkillId1": "160",
          "battleSkillId2": "3",
          "leaderSkillId": "2",
          "runSkillId1": "0",
          "hp": "1478",
          "hpMax": "3696",
          "attack": "2587",
          "attackMax": "6468",
          "attackBehaveNum": "0",
          "defense": "1214",
          "defenseMax": "3036",
          "speed": "100",
          "speedMax": "100",
          "hitLot": "10000",
          "avoidanceLot": "780",
          "criticalLot": "1565",
          "criticalDamageLot": "16800",
          "cost": "11",
          "price": "1200",
          "fusionExp": "300",
          "fusionMaterialFlg": "0",
          "charaProfileId": "101",
          "defaultUnlockBit": "0",
          "fusionRuleId": null,
          "createTime": "2015-04-19 17:37:12",
          "createUserId": "1",
          "updateTime": "2015-04-19 17:37:12",
          "updateUserId": "1",
          "translated": "0"
        }
]
